language: python
sudo: required
python:
- '3.6.5'
services:
- docker
git:
  depth: 1
addons:
  firefox: latest

env:
  # otherwise we need to start an X-server, see https://docs.travis-ci.com/user/gui-and-headless-browsers/
  - MOZ_HEADLESS=1

install:
- pip install capybara-py selenium

# Geckodriver needed  for integration tests
- wget https://github.com/mozilla/geckodriver/releases/download/v0.21.0/geckodriver-v0.21.0-linux64.tar.gz
- mkdir geckodriver
- tar -xzf geckodriver-v0.21.0-linux64.tar.gz -C geckodriver
- export PATH=$PATH:$PWD/geckodriver

script:
# Docker build does both npm test and ./manage.py test
- docker build . && bin/integration-test

notifications:
  slack:
    secure: kSu7kORuHC4ifkF/XyHg5Cm9Ks/ncminPL5GTdlzIXFjwsGQ2wsNSXeZ5z0PxRI6MINXHbtrrn2rNA+UhXexZ6p1RpjgbGYaoktqsAG6mXzFU9Pf4ytPVk+dJdGvtOiS9sz3OvyDgllZn/x75hG2o5Ky+fDSkSoOKzLv8AGYO4UpIORdtTJZVYqccS94I+hdIoKdh8G3kqkKsfkaXxYZY174t6xfvO3oAOEIR4KQouFHsjfHBNPA+7fI/BV1ortfweBQvWz32b1C0V/xpHPt+ATlTbzBh89X5myZxV6TB1/wwkpgI4FLLjEJCslwAF+KePvK/CDaYgLMYkQPNond12+Wyjwqerz7Zq2mPSrrWQMJvX8CvG23xhzqj8G9sOYHfAVHJ5FC3lSEECzdwVaEPqTs2BcSwrNOW+PVEnrcgdf9BxUCztl+FzRaj+rAYWW+ADd3FseQAiTyV1zIrZifXxztNM99p7d5rg+BTvDCkoHU6x1RWGKcde4oB4h7+W5NEXvEluMas1os5XEOrfVwGiozZgwhymD/inWpimK8RyxDCd+gPVYrwjzAzaAnnJG+YcyBdDu8kKBbvYMaP7Uk8YJYwvqB3cFY4uo0wN6SUo2iYNGrW2sdhriPqzehF5FPDpIYrL2hlP/APeMHyRs/esgZvZz6L6HM+P3myKPxAlA=
