language: python
python: 
  - "3.5"
node_js:
  - "7.7"
install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
  - "npm install -g"
  - "pip install -r requirements.txt"
  - "pip install -r requirements-dev.txt"
  - "git submodule update --init --recursive"
  - "git submodule update --remote"
script:
  - python manage.py test
  - npm test
git:
  submodules: true
