# See https://cloud.google.com/cloud-build/docs/build-debug-locally for debug
# instructions.
#
# The copy/paste-able command:
# gcloud config configurations activate workbenchdata-ci  # set PROJECT_ID
# cloud-build-local --dryrun=false --substitutions COMMIT_SHA=abc123 .
timeout: 2400s
options:
  machineType: N1_HIGHCPU_8
steps:

# Build new Docker images.
#
# Does in-process verifications like `npm test` and `black`.
- name: 'gcr.io/cloud-builders/docker:20.10.3'
  args: [ 'buildx', 'bake', '-f', 'docker-bake.hcl', 'default', 'unittest', 'integration-test' ]
  env:
  - 'REPOSITORY=gcr.io/$PROJECT_ID'
  - 'TAG=$COMMIT_SHA'

# Unit-test
- name: 'docker/compose:1.28.6'
  args: [ '-f', 'server/tests/docker-compose.yml',
          'run',
          'migrate'
        ]
  env:
    - 'PROJECT_ID=$PROJECT_ID'
    - 'COMMIT_SHA=$COMMIT_SHA'
- name: 'docker/compose:1.28.6'
  args: [ '-f', 'server/tests/docker-compose.yml',
          'run',
          'unittest'
        ]
  env:
    - 'PROJECT_ID=$PROJECT_ID'
    - 'COMMIT_SHA=$COMMIT_SHA'

# Integration-test: upload-assets+migrate, then run the integration-test image
- name: 'docker/compose:1.28.6'
  args: [ '-f', 'integrationtests/docker-compose.yml',
          '-f', 'integrationtests/docker-compose.cloudbuild-override.yml',
          'run',
          'upload-assets'
        ]
  env:
    - 'PROJECT_ID=$PROJECT_ID'
    - 'COMMIT_SHA=$COMMIT_SHA'
- name: 'docker/compose:1.28.6'
  args: [ '-f', 'integrationtests/docker-compose.yml',
          '-f', 'integrationtests/docker-compose.cloudbuild-override.yml',
          'run',
          'migrate'
        ]
  env:
    - 'PROJECT_ID=$PROJECT_ID'
    - 'COMMIT_SHA=$COMMIT_SHA'
- name: 'docker/compose:1.28.6'
  args: [ '-f', 'integrationtests/docker-compose.yml',
          '-f', 'integrationtests/docker-compose.cloudbuild-override.yml',
          'run',
          '--use-aliases',
          'integration-test'
        ]
  env:
    - 'PROJECT_ID=$PROJECT_ID'
    - 'COMMIT_SHA=$COMMIT_SHA'

images:
- 'gcr.io/$PROJECT_ID/migrate:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/upload-assets:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/fetcher:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/renderer:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/cron:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/frontend:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/tusd-hooks:$COMMIT_SHA'
