version: '3.4'

# https://github.com/docker/compose/issues/1896 gives docker-compose's rationale
# for keeping our 'migrate' and 'test' runners outside of docker-compose.yml.
services:
  migrate:
    build: &python-build
      context: .
      target: pydev
    volumes: &python-volumes
      - ./:/app/:rw
      - virtualenvs:/root/.local/share/virtualenvs/:rw
    environment: &pydev-environment
      PYTHONUNBUFFERED: '1'
      CJW_DB_HOST: database
      CJW_REDIS_HOST: redis
      CJW_DB_PASSWORD: cjworkbench
      CJW_SECRET_KEY: cjw-secret-key
      CJW_MOCK_EMAIL: 'True'
    networks: [ 'dev' ]
    depends_on: [ 'database', 'redis' ]
    command: [ 'sh', '-c', 'pipenv sync --dev && bin/migrate-prod' ]

  unittest:
    build: *python-build
    volumes: *python-volumes
    environment:
      <<: *pydev-environment
      CJW_DB_HOST: testdatabase
      CJW_REDIS_HOST: testredis
    networks: [ 'test' ]
    depends_on: [ 'testdatabase', 'testredis' ]
    command: [ 'pipenv', 'run', 'python', './manage.py', 'test' ]
