version: '3.4'

# https://github.com/docker/compose/issues/1896 gives docker-compose's rationale
# for keeping our 'migrate' and 'test' runners outside of docker-compose.yml.
services:
  migrate:
    build:
      context: .
      target: pydev
    volumes:
      - ./:/app/:rw
      - virtualenvs:/root/.local/share/virtualenvs/:rw
    environment:
      PYTHONUNBUFFERED: '1'
      CJW_DB_HOST: database
      CJW_REDIS_HOST: redis
      CJW_DB_PASSWORD: cjworkbench
      CJW_SECRET_KEY: cjw-secret-key
      MINIO_ACCESS_KEY: minio_access
      MINIO_SECRET_KEY: minio_secret
      MINIO_URL: http://minio
      MINIO_BUCKET_PREFIX: dev
    networks: [ 'dev' ]
    depends_on: [ 'database', 'redis' ]
    command: [ 'sh', '-c', 'pipenv sync --dev && pipenv run bin/migrate-prod' ]

  develop-module:
    # Basically a copy-paste of 'migrate' ... but with $MODULE mounted
    build:
      context: .
      target: pydev
    volumes:
      - ./:/app/:rw
      - virtualenvs:/root/.local/share/virtualenvs/:rw
      - ../${MODULE:-x}:/${MODULE:-x}:ro
    environment:
      PYTHONUNBUFFERED: '1'
      CJW_DB_HOST: database
      CJW_REDIS_HOST: redis
      CJW_DB_PASSWORD: cjworkbench
      CJW_SECRET_KEY: cjw-secret-key
      MINIO_ACCESS_KEY: minio_access
      MINIO_SECRET_KEY: minio_secret
      MINIO_URL: http://minio
      MINIO_BUCKET_PREFIX: dev
    networks: [ 'dev' ]
    depends_on: [ 'database', 'redis' ]
    command: [ 'sh', '-c', 'pipenv sync --dev && pipenv run bin/migrate-prod' ]

  unittest:
    # It'd be nice to use YAML anchors to copy these parameters ... but
    # PyCharm's YAML parser seems to die when we use YAML anchors.
    build:
      context: .
      target: pydev
    volumes:
      - ./:/app/:rw
      - virtualenvs:/root/.local/share/virtualenvs/:rw
    environment:
      PYTHONUNBUFFERED: '1'
      CJW_DB_HOST: testdatabase
      CJW_REDIS_HOST: testredis
      CJW_DB_PASSWORD: cjworkbench
      CJW_SECRET_KEY: cjw-secret-key
      MINIO_ACCESS_KEY: minio_access
      MINIO_SECRET_KEY: minio_secret
      MINIO_URL: http://testminio
      MINIO_BUCKET_PREFIX: test
    networks: [ 'test' ]
    depends_on: [ 'testdatabase', 'testredis' ]
    command: [ 'pipenv', 'run', 'python', './manage.py', 'test' ]
