version: '3.4'

# https://github.com/docker/compose/issues/1896 gives docker-compose's rationale
# for keeping our 'migrate' and 'test' runners outside of docker-compose.yml.
services:
  migrate:
    build:
      context: .
      target: pydev
    volumes:
      - ./:/app/:cached
      - virtualenvs:/root/.local/share/virtualenvs/:rw
    environment: &django-env
      PYTHONUNBUFFERED: '1'
      ASGI_THREADS: '3'
      CJW_DB_HOST: database
      CJW_RABBITMQ_HOST: amqp://guest:guest@rabbitmq
      CJW_DB_PASSWORD: cjworkbench
      CJW_SECRET_KEY: cjw-secret-key
      MINIO_ACCESS_KEY: minio_access
      MINIO_SECRET_KEY: minio_secret
      MINIO_URL: http://minio:9000
      MINIO_BUCKET_PREFIX: dev
    networks: [ 'dev' ]
    depends_on: [ 'database', 'rabbitmq', 'minio' ]
    command: [ 'sh', '-c', 'while ! curl --silent -I $$MINIO_URL >/dev/null; do sleep 0.1; done; mc config host add workbench $$MINIO_URL minio_root_access minio_root_secret && mc admin user add workbench $$MINIO_ACCESS_KEY $$MINIO_SECRET_KEY && mc admin policy set workbench readwrite user=$$MINIO_ACCESS_KEY && pipenv sync --dev && pipenv run bin/migrate-prod' ]

  develop-module:
    # Basically a copy-paste of 'migrate' ... but with $MODULE mounted
    build:
      context: .
      target: pydev
    volumes:
      - type: bind
        source: ./
        target: /app/
        consistency: cached
      - type: bind
        source: ../${MODULE:-x}/
        target: /${MODULE:-x}/
        consistency: cached
        read_only: true
      - virtualenvs:/root/.local/share/virtualenvs/:rw
    security_opt:
      - seccomp=docker/pyspawner-seccomp-profile.json
    cap_add: [ SYS_ADMIN ] # for cjwkernel.kernel to overlay-mount chroots (on k8s we use an init container instead)
    environment:
      <<: *django-env
    networks: [ 'dev' ]
    depends_on: [ 'database', 'rabbitmq', 'minio' ]

  pydev:
    # Run Python commands without depending on other services
    build:
      context: .
      target: pydev
    volumes:
      - type: bind
        source: ./
        target: /app/
        consistency: cached
      - virtualenvs:/root/.local/share/virtualenvs/:rw
    security_opt:
      - seccomp=docker/pyspawner-seccomp-profile.json
    cap_add:
      - SYS_ADMIN # for cjwkernel.kernel to overlay-mount chroots (on k8s we use an init container instead)
      - NET_ADMIN # for pyspawner to create new network namespace without access to private network
    environment:
      <<: *django-env
    networks: [ 'dev' ]

  unittest:
    # It'd be nice to use YAML anchors to copy these parameters ... but
    # PyCharm's YAML parser seems to die when we use YAML anchors.
    build:
      context: .
      target: pydev
    volumes:
      - type: bind
        source: ./
        target: /app/
        consistency: cached
      - virtualenvs:/root/.local/share/virtualenvs/:rw
    security_opt:
      - seccomp=docker/pyspawner-seccomp-profile.json
    cap_add:
      - SYS_ADMIN # for cjwkernel.kernel to overlay-mount chroots (on k8s we use an init container instead)
      - NET_ADMIN # for pyspawner to create new network namespace without access to private network
    environment:
      <<: *django-env
      CJW_DB_HOST: testdatabase
      CJW_RABBITMQ_HOST: amqp://guest:guest@testrabbitmq
      MINIO_URL: http://testminio:9000
    networks: [ 'test' ]
    depends_on: [ 'testdatabase', 'testrabbitmq', 'testminio' ]
    entrypoint: 'bin/unittest-entrypoint.sh'
