# Bring up all the pieces necessary to run the workbench
# Data persists in Docker volumes and in local dir

# This file passes through all necessary env variables to requisite
# Docker containers and makes them available when running commands via
# `docker exec`.

version: '3.4'

services:
  database:
    image: postgres:10.4
    environment:
      - POSTGRES_USER=cjworkbench
      - POSTGRES_PASSWORD=cjworkbench
      - POSTGRES_DB=cjworkbench
      - PGDATA=/var/lib/postgresql/data/10.4
    networks: [ 'dev' ]
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "psql -h localhost -U cjworkbench -c '\\q' "]
      interval: 1s
      retries: 3
      start_period: 120s

  rabbitmq:
    image: rabbitmq:3.7.8-management
    ports: [ '15672' ] # open management port, for debugging
    networks: [ 'dev' ]
    healthcheck:
      test: [ "CMD-SHELL", "rabbitmq-diagnostics status | grep -q listeners.*clustering.*amqp" ]
      interval: 1s
      retries: 3
      start_period: 120s

  minio:
    image: minio/minio:RELEASE.2018-09-11T01-39-21Z
    networks: [ 'dev' ]
    ports: [ '8001:9000' ]
    environment:
      MINIO_ACCESS_KEY: minio_access
      MINIO_SECRET_KEY: minio_secret
    volumes:
      - minio_data:/data
    command: server /data

  webpack:
    build:
      context: .
      target: jsbase
    volumes:
      # Migrate 
      - ./:/app/:rw
      - node_modules:/app/node_modules:rw
      - jest_cache:/tmp/jest_0:rw
    networks: [ 'dev' ]
    command: node_modules/.bin/webpack --mode development --watch

  frontend:
    build:
      context: .
      target: pydev
    volumes:
      - ./:/app/:rw
      - virtualenvs:/root/.local/share/virtualenvs/:rw
    environment:
      PYTHONUNBUFFERED: '1'
      CJW_DB_HOST: database
      CJW_RABBITMQ_HOST: amqp://guest:guest@rabbitmq/
      CJW_DB_PASSWORD: cjworkbench
      CJW_SECRET_KEY: cjw-secret-key
      MINIO_ACCESS_KEY: minio_access
      MINIO_SECRET_KEY: minio_secret
      MINIO_URL: http://minio:9000
      MINIO_EXTERNAL_URL: http://localhost:8001
      MINIO_BUCKET_PREFIX: dev
      CACHE_MODULES: "${CACHE_MODULES:-}"
    ports: [ '8000:8080' ]
    networks: [ 'dev' ]
    depends_on: [ 'database', 'rabbitmq', 'minio' ]
    command: [ 'pipenv', 'run', 'python', './manage.py', 'runserver', '--insecure', '0.0.0.0:8080' ]

  worker:
    # It'd be nice to use YAML anchors to copy these parameters ... but
    # PyCharm's YAML parser seems to die when we use YAML anchors.
    build:
      context: .
      target: pydev
    volumes:
      - ./:/app/:rw
      - virtualenvs:/root/.local/share/virtualenvs/:rw
    environment:
      PYTHONUNBUFFERED: '1'
      CJW_DB_HOST: database
      CJW_RABBITMQ_HOST: amqp://guest:guest@rabbitmq/
      CJW_DB_PASSWORD: cjworkbench
      CJW_SECRET_KEY: cjw-secret-key
      MINIO_ACCESS_KEY: minio_access
      MINIO_SECRET_KEY: minio_secret
      MINIO_URL: http://minio:9000
      MINIO_BUCKET_PREFIX: dev
      CACHE_MODULES: "${CACHE_MODULES:-}"
    depends_on: [ 'database', 'rabbitmq', 'minio' ]
    networks: [ 'dev' ]
    command: [ 'pipenv', 'run', 'python', './manage.py', 'worker' ]

  # docker-compose won't obey `services[*].deploy.replicas=2`, so here's an
  # exact copy of the `worker` service.
  #
  # We deploy two copies because A) a dev machine tends to have >1 CPU, and
  # B) it's great to test contention and locking.
  worker2:
    # It'd be nice to use YAML anchors to copy these parameters ... but
    # PyCharm's YAML parser seems to die when we use YAML anchors.
    build:
      context: .
      target: pydev
    volumes:
      - ./:/app/:rw
      - virtualenvs:/root/.local/share/virtualenvs/:rw
    environment:
      PYTHONUNBUFFERED: '1'
      CJW_DB_HOST: database
      CJW_RABBITMQ_HOST: amqp://guest:guest@rabbitmq/
      CJW_DB_PASSWORD: cjworkbench
      CJW_SECRET_KEY: cjw-secret-key
      MINIO_ACCESS_KEY: minio_access
      MINIO_SECRET_KEY: minio_secret
      MINIO_URL: http://minio:9000
      MINIO_BUCKET_PREFIX: dev
      CACHE_MODULES: "${CACHE_MODULES:-}"
    depends_on: [ 'database', 'rabbitmq', 'minio' ]
    networks: [ 'dev' ]
    command: [ 'pipenv', 'run', 'python', './manage.py', 'worker' ]


  cron:
    # It'd be nice to use YAML anchors to copy these parameters ... but
    # PyCharm's YAML parser seems to die when we use YAML anchors.
    build:
      context: .
      target: pydev
    volumes:
      - ./:/app/:rw
      - virtualenvs:/root/.local/share/virtualenvs/:rw
    environment:
      PYTHONUNBUFFERED: '1'
      CJW_DB_HOST: database
      CJW_RABBITMQ_HOST: amqp://guest:guest@rabbitmq/
      CJW_DB_PASSWORD: cjworkbench
      CJW_SECRET_KEY: cjw-secret-key
      MINIO_ACCESS_KEY: minio_access
      MINIO_SECRET_KEY: minio_secret
      MINIO_URL: http://minio:9000
      MINIO_BUCKET_PREFIX: dev
      CACHE_MODULES: "${CACHE_MODULES:-}"
    depends_on: [ 'database', 'rabbitmq', 'minio' ]
    networks: [ 'dev' ]
    command: [ 'pipenv', 'run', 'python', './manage.py', 'cron' ]

  testdatabase:
    image: postgres:10.4
    environment:
      - POSTGRES_USER=cjworkbench
      - POSTGRES_PASSWORD=cjworkbench
      - POSTGRES_DB=cjworkbench
      - PGDATA=/var/lib/postgresql/data/10.4
    networks: [ 'test' ]
    # no volumes: we wipe this DB a lot

  testrabbitmq:
    image: rabbitmq:3.7.8
    networks: [ 'test' ]

  testminio:
    image: minio/minio:RELEASE.2018-09-11T01-39-21Z
    networks: [ 'test' ]
    environment:
      MINIO_ACCESS_KEY: minio_access
      MINIO_SECRET_KEY: minio_secret
    command: server /data

networks:
  dev: {}
  test: {}

volumes:
  dbdata: {}
  minio_data: {}
  virtualenvs: {}
  # Let's not make node_modules a bind mount: Windows bind mounts seem
  # to behave a bit differently from Linux bind mounts. Use a Docker volume
  # instead.
  node_modules: {}
  jest_cache: {}
