version: '3.4'
# These settings are specific to cloudbuild mode.
# See docker-compose.override.yml for dev mode.
#
# We use tagged images in cloudbuild mode: we want to test the exact images
# we're about to publish. And we can rely on $PROJECT_ID and $COMMIT_SHA,
# because cloudbuild provides them.
services:
  upload-assets:
    image: 'gcr.io/${PROJECT_ID}/upload-assets:${COMMIT_SHA}'

  migrate:
    image: 'gcr.io/${PROJECT_ID}/migrate:${COMMIT_SHA}'

  fetcher:
    image: 'gcr.io/${PROJECT_ID}/fetcher:${COMMIT_SHA}'

  renderer:
    image: 'gcr.io/${PROJECT_ID}/renderer:${COMMIT_SHA}'

  cron:
    image: 'gcr.io/${PROJECT_ID}/cron:${COMMIT_SHA}'

  cron-delta-deleter:
    image: 'gcr.io/${PROJECT_ID}/cron:${COMMIT_SHA}'

  cron-expired-session-deleter:
    image: 'gcr.io/${PROJECT_ID}/cron:${COMMIT_SHA}'

  cron-lesson-autoupdate-disabler:
    image: 'gcr.io/${PROJECT_ID}/cron:${COMMIT_SHA}'

  frontend:
    image: 'gcr.io/${PROJECT_ID}/frontend:${COMMIT_SHA}'

  integration-test:
    image: 'gcr.io/${PROJECT_ID}/integration-test:${COMMIT_SHA}'
