#!/bin/bash

ENV=${1:?"Usage: $0 ENVIRONMENT SHA"}
SHA=${2:?"Usage: $0 ENVIRONMENT SHA"}

echo -n "Running migrations for $SHA on $ENV..." >&2
kubectl -n $ENV delete job migrate-job 2>/dev/null || true
kubectl -n $ENV delete pod -lapp=migrate-job 2>/dev/null || true
cat "$(dirname "$0")"/kubernetes/migrate.yaml \
      | sed -e "s/:latest/:$SHA/" \
      | kubectl -n $ENV apply -f -
until [ "$(kubectl -n $ENV get jobs migrate-job --no-headers -o custom-columns=status:status.succeeded)" = "1" ]; do
  echo -n '.' >&2
  sleep 1
done
echo ' done' >&2

echo -n "Setting frontend and backend images to $SHA on $ENV..." >&2
kubectl -n $ENV set image deployment/backend-deployment backend=gcr.io/cj-workbench/backend:$SHA
kubectl -n $ENV set image deployment/frontend-deployment frontend=gcr.io/cj-workbench/frontend:$SHA
echo -n ' done' >&2
echo -n >&2
echo 'Watch deployment at: ' >&2
echo 'Backend: https://console.cloud.google.com/kubernetes/deployment/us-central1-b/workbench/$ENV/backend-deployment?project=cj-workbench' >&2
echo 'Frontend: https://console.cloud.google.com/kubernetes/deployment/us-central1-b/workbench/$ENV/frontend-deployment?project=cj-workbench' >&2
