#!/bin/sh

set -e

ENV=${1:?"Usage: $0 ENVIRONMENT SHA"}
SHA=${2:?"Usage: $0 ENVIRONMENT SHA"}

run_migrations() {
  echo -n "Running migrations for $SHA on $ENV..." >&2
  kubectl -n $ENV delete pod migrate-$SHA 2>/dev/null || true # delete if already running
  overrides=$(cat "$(dirname "$0")"/kubernetes/migrate.json | sed -e "s/\\\$SHA/$SHA/")
  kubectl \
    -n $ENV \
    run migrate-$SHA \
    --image="gcr.io/cj-workbench/migrate:$SHA" \
    -i --rm --wait --quiet \
    --restart=Never \
    --overrides="$overrides"
  echo ' done' >&2
}

run_migrations >&2

echo -n "Setting frontend, worker and cron images to $SHA on $ENV..." >&2
kubectl -n $ENV set image deployment/worker-deployment worker=gcr.io/cj-workbench/worker:$SHA >/dev/null
kubectl -n $ENV set image deployment/cron-deployment cron=gcr.io/cj-workbench/cron:$SHA >/dev/null
kubectl -n $ENV set image deployment/frontend-deployment frontend=gcr.io/cj-workbench/frontend:$SHA >/dev/null
echo ' done' >&2

echo -n 'Waiting for rollout to finish...' >&2
kubectl -n $ENV rollout status deployment/worker-deployment >/dev/null
echo -n '.' >&2
kubectl -n $ENV rollout status deployment/frontend-deployment >/dev/null
echo -n '.' >&2
kubectl -n $ENV rollout status deployment/cron-deployment >/dev/null
echo ' done' >&2

echo >&2
echo 'Inspect services at https://console.cloud.google.com/kubernetes/workload?project=cj-workbench' >&2
