#!/bin/sh

set -e

ENV=${1:?"Usage: $0 ENVIRONMENT"}

echo "WARNING: after wiping the cache, there is no way to check for rendered changes. That means the next time each workflow is executed, it will not email change notifications."
read -r -p "Are you okay with skipping some notifications? [y/N] " response
if [ "$response" != "y" ]; then
  echo "You did not respond \"y\". Bye."
  exit 0
fi

echo "Locking all workflows and clearing all steps' cached output..."

DATABASE_POD="$(kubectl -n "$ENV" get pods -lapp=database-app -oname)"

kubectl -n "$ENV" exec -it "$DATABASE_POD" -- psql -Ucjworkbench -c "BEGIN; SELECT id FROM server_workflow FOR UPDATE; UPDATE server_wfmodule SET cached_render_result_delta_id=NULL, cached_render_result_errors='[]'::JSONB, cached_render_result_error='', cached_render_result_json='null'::BYTEA, cached_render_result_quick_fixes='[]'::JSONB, cached_render_result_status=NULL, cached_render_result_columns=NULL, cached_render_result_nrows=NULL; COMMIT"

echo "Deleting files created before [FIXME] from minio..."
echo "TODO. This step isn't done. That means we're wasting disk space with files we'll never read."
echo "TODO build a garbage-collection scheme to clear these files."
