#!/bin/sh

set -e

ENV=${1:?"Usage: $0 ENVIRONMENT"}

if [ "$ENV" = "production" ]; then
  CLUSTER="gke_workbenchdata-production_us-central1-b_workbench"
else
  CLUSTER="gke_workbench-staging_us-central1-b_workbench"
fi

KUBECTL="kubectl.1.19 --cluster $CLUSTER"
FRONTEND_POD="$($KUBECTL get pods -lapp=frontend-app -oname | head -n1 | cut -d/ -f2)"

$KUBECTL exec -it "$FRONTEND_POD" -c frontend -- sh -c 'PGPASSWORD="$CJW_DB_PASSWORD" PGUSER="cjworkbench" PGHOST="localhost" PGDATABASE="cjworkbench" exec psql'
