#!/bin/bash

set -e
# test for needed commands; "set -e" means we'll exit if any are missing
type cut >/dev/null
type git >/dev/null
type kubectl >/dev/null
type tail >/dev/null

find_sha1_on_env() {
  env="$1"
  kubectl -n $env get deployment frontend-deployment \
      -o custom-columns=x:'{.spec.template.spec.containers[0].image}' \
    | tail -n1 \
    | cut -d: -f2
}

describe_env() {
  env="$1"
  sha1=$(find_sha1_on_env "$env")
  git log "$sha1" --oneline --no-walk
}

echo 'STAGING:' $(describe_env staging)
echo 'PRODUCTION:' $(describe_env production)
