#!/bin/bash

set -e
# test for needed commands; "set -e" means we'll exit if any are missing
type curl >/dev/null
type git >/dev/null
type jq >/dev/null
type sed >/dev/null
type kubectl >/dev/null

find_latest_passing_sha1_on_master() {
  echo 'Finding latest passing sha1 on master...' >&2
  commits=$(curl -s 'https://api.github.com/repos/CJWorkbench/cjworkbench/commits' | jq -r '.[] | .sha')

  for commit in $commits; do
    echo -n "  google-container-builder conclusion for $commit:" >&2
    conclusion=$(curl -s --header 'Accept: application/vnd.github.antiope-preview+json' "https://api.github.com/repos/CJWorkbench/cjworkbench/commits/$commit/check-runs" | jq -r '.check_runs[] | select(.app.slug == "google-cloud-build") | .conclusion')
    echo " $conclusion" >&2
    if [ "$conclusion" = "success" ]; then
      echo $commit
      return
    fi
  done

  echo 'There are no recent passing images to deploy. Exiting.' >&2
  exit 1
}

SHA=$(find_latest_passing_sha1_on_master)

"$(dirname "$0")"/advanced-deploy staging $SHA
