apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cert-manager-deployment
  namespace: kube-system
  labels:
    app: cert-manager-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cert-manager-app
  template:
    metadata:
      labels:
        app: cert-manager-app
      annotations:
    spec:
      serviceAccountName: cert-manager-service-account
      containers:
        - name: cert-manager
          image: quay.io/jetstack/cert-manager-controller:v0.3.2
          imagePullPolicy: IfNotPresent
          args:
            - --default-acme-issuer-challenge-type=dns01
            - --default-acme-issuer-dns01-provider-name=clouddns
            - --default-issuer-kind=ClusterIssuer
            - --default-issuer-name=letsencrypt-prod
          env:
            - name: POD_NAMESPACE
              value: kube-system
