apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: adam@adamhooper.com
    privateKeySecretRef:
      name: letsencrypt-prod-secret
    dns01:
      providers:
        - name: clouddns
          clouddns:
            serviceAccountSecretRef:
              name: clouddns-svc-secret
              key: service-account.json
            project: cj-workbench
