kind: Service
apiVersion: v1
metadata:
  name: minio-service
  annotations:
    cloud.google.com/neg: '{"ingress": true}'  # https://cloud.google.com/kubernetes-engine/docs/how-to/container-native-load-balancing
spec:
  selector:
    app: minio-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
