# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-08 23:10
from __future__ import unicode_literals

import cjworkbench.models.GoogleCreds
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cjworkbench', '0004_auto_20171030_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlecredentials',
            name='flow',
            field=cjworkbench.models.GoogleCreds.FlowField(null=True),
        ),
    ]
