# Generated by Django 3.1.5 on 2021-01-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cjworkbench", "0004_plan_and_stripe_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="stripe_customer_id",
            field=models.SlugField(blank=True, default=None, null=True),
        ),
    ]
