# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-09 00:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("cjworkbench", "0005_googlecredentials_flow")]

    operations = [
        migrations.AlterField(
            model_name="googlecredentials",
            name="id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="google_credentials",
                to=settings.AUTH_USER_MODEL,
            ),
        )
    ]
