# Generated by Django 3.1.5 on 2021-01-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cjworkbench", "0005_auto_20210113_1624"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="stripe_active",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plan",
            name="stripe_amount",
            field=models.PositiveIntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plan",
            name="stripe_currency",
            field=models.CharField(default="usd", max_length=3),
            preserve_default=False,
        ),
    ]
