# Generated by Django 3.1.5 on 2021-01-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cjworkbench", "0006_auto_20210126_1943"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="stripe_product_id",
            field=models.SlugField(),
        ),
    ]
