# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-07 16:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("cjworkbench", "0007_auto_20180109_0014")]

    operations = [
        migrations.AlterField(
            model_name="googlecredentials",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="google_credentials",
                to=settings.AUTH_USER_MODEL,
            ),
        )
    ]
