# Generated by Django 3.1.6 on 2021-02-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cjworkbench", "0008_auto_20210127_1817"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="max_delta_age_in_days",
            field=models.IntegerField(
                default=31,
                help_text="Number of days a change ('Delta') lives in the undo history. Workbench deletes actions that haven't been undone in a long time.",
            ),
        ),
    ]
