# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-08 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("cjworkbench", "0008_auto_20180607_1602")]

    operations = [
        migrations.RemoveField(model_name="googlecredentials", name="user"),
        migrations.DeleteModel(name="GoogleCredentials"),
    ]
