# Generated by Django 3.1.6 on 2021-02-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    """Change "Plan" to become "Price"+"Product".

    Our initial deploy simplified Stripe's models. Now, we adhere to them
    because we want two Prices on one Product.
    """

    dependencies = [
        ("cjworkbench", "0009_plan_max_delta_age_in_days"),
    ]

    operations = [
        migrations.RenameModel("Plan", "Price"),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stripe_product_id", models.SlugField()),
                ("stripe_product_name", models.TextField()),
                (
                    "max_fetches_per_day",
                    models.IntegerField(
                        default=1000,
                        help_text="Applies to the sum of all the user's Workflows. One fetch every 5min = 288 fetches per day.",
                    ),
                ),
                (
                    "max_delta_age_in_days",
                    models.IntegerField(
                        default=31,
                        help_text="Number of days a change ('Delta') lives in the undo history. Workbench deletes actions that haven't been undone in a long time.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product (edit/delete in Stripe dashboard)",
                "verbose_name_plural": "Products (create/edit/delete in Stripe dashboard)",
                "db_table": "product",
            },
        ),
        migrations.AlterModelOptions(
            name="price",
            options={
                "verbose_name": "Price (edit/delete in Stripe dashboard)",
                "verbose_name_plural": "Prices (create/edit/delete in Stripe dashboard)",
            },
        ),
        migrations.AlterModelTable(
            name="price",
            table="price",
        ),
        migrations.AddField(
            model_name="price",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=models.deletion.PROTECT,
                related_name="prices",
                to="cjworkbench.product",
            ),
        ),
        migrations.RunSQL(
            [
                """
                INSERT INTO product (
                    stripe_product_id,
                    stripe_product_name,
                    max_fetches_per_day,
                    max_delta_age_in_days
                )
                SELECT DISTINCT
                    stripe_product_id,
                    stripe_product_name,
                    max_fetches_per_day,
                    max_delta_age_in_days
                FROM price
                """,
                """
                UPDATE price
                SET product_id = (
                    SELECT product.id
                    FROM product
                    WHERE product.stripe_product_id = price.stripe_product_id
                    LIMIT 1
                )
                """,
            ],
            elidable=True,
        ),
        migrations.AlterField(
            model_name="price",
            name="product",
            field=models.ForeignKey(
                on_delete=models.deletion.PROTECT,
                related_name="prices",
                to="cjworkbench.product",
            ),
        ),
        migrations.RenameField(
            model_name="subscription",
            old_name="plan",
            new_name="price",
        ),
        migrations.RemoveField(
            model_name="price",
            name="max_delta_age_in_days",
        ),
        migrations.RemoveField(
            model_name="price",
            name="max_fetches_per_day",
        ),
        migrations.RemoveField(
            model_name="price",
            name="stripe_product_id",
        ),
        migrations.RemoveField(
            model_name="price",
            name="stripe_product_name",
        ),
        migrations.AddField(
            model_name="price",
            name="stripe_interval",
            field=models.TextField(
                choices=[("month", "month"), ("year", "year")], default="month"
            ),
        ),
    ]
