# Generated by Django 2.2.8 on 2019-12-16 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("server", "0001_squashed_0038_auto_20190926_1255")]

    operations = [
        migrations.RemoveField(
            model_name="wfmodule", name="cached_render_result_error"
        ),
        migrations.RemoveField(
            model_name="wfmodule", name="cached_render_result_quick_fixes"
        ),
    ]
