# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 22:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='ParameterSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='ParameterVal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('STR', 'String'), ('NUM', 'Numeric')], default='NUM', max_length=3)),
                ('numDefaultVal', models.FloatField(verbose_name='numVal')),
                ('strVal', models.CharField(blank=True, max_length=20, verbose_name='strVal')),
            ],
        ),
        migrations.RemoveField(
            model_name='wfmodule',
            name='workflow',
        ),
        migrations.AddField(
            model_name='workflow',
            name='modules',
            field=models.ManyToManyField(to='server.WfModule'),
        ),
        migrations.RemoveField(
            model_name='wfmodule',
            name='parameters',
        ),
        migrations.AddField(
            model_name='parameterspec',
            name='defaultVal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='server.ParameterVal'),
        ),
        migrations.AddField(
            model_name='module',
            name='parameterSpecs',
            field=models.ManyToManyField(to='server.ParameterSpec'),
        ),
        migrations.AddField(
            model_name='wfmodule',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='server.Module'),
        ),
        migrations.AddField(
            model_name='wfmodule',
            name='parameters',
            field=models.ManyToManyField(to='server.ParameterVal'),
        ),
    ]
