# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-05 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_squashed_0150_auto_20181205_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedobject',
            name='bucket',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='storedobject',
            name='key',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='storedobject',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
