# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-10 14:51
from __future__ import unicode_literals

from django.db import migrations


def delete_module_versions(apps, schema_editor):
    from cjwstate import minio

    # Delete from database
    ModuleVersion = apps.get_model("server", "ModuleVersion")
    ModuleVersion.objects.filter(id_name="convert-text").delete()

    # Delete from S3
    try:
        minio.remove_recursive(minio.ExternalModulesBucket, "convert-text/")
    except minio.error.NoSuchBucket:
        pass  # we're unit-testing and the bucket doesn't exist


class Migration(migrations.Migration):
    """
    Forgot to delete the ModuleVersions in the previous migration.
    """

    dependencies = [("server", "0002_internalize_converttotext")]

    operations = [migrations.RunPython(delete_module_versions, elidable=True)]
