# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-10 14:51
from __future__ import unicode_literals

from django.db import migrations
from server import minio


def delete_module_versions(apps, schema_editor):
    # Delete from database
    ModuleVersion = apps.get_model('server', 'ModuleVersion')
    ModuleVersion.objects.filter(id_name='convert-text').delete()

    # Delete from S3
    minio.remove_recursive(minio.ExternalModulesBucket, 'convert-text/')


class Migration(migrations.Migration):
    """
    Forgot to delete the ModuleVersions in the previous migration.
    """

    dependencies = [
        ('server', '0002_internalize_converttotext'),
    ]

    operations = [
        migrations.RunPython(delete_module_versions, elidable=True)
    ]
