# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20161102_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
