# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20161121_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='modules',
        ),
    ]
