# Generated by Django 2.2.9 on 2020-02-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("server", "0003_auto_20200131_2016")]

    operations = [
        migrations.AlterField(
            model_name="storedobject",
            name="bucket",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="bucket",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
