# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-13 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_move_stored_objects_to_s3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storedobject',
            name='file',
        ),
        migrations.AlterField(
            model_name='storedobject',
            name='bucket',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='storedobject',
            name='key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
