# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_workflow_modules'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameterval',
            old_name='numDefaultVal',
            new_name='numVal',
        ),
        migrations.AddField(
            model_name='wfmodule',
            name='order',
            field=models.IntegerField(default=0, verbose_name='order'),
            preserve_default=False,
        ),
    ]
