# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_auto_20161121_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='modules',
        ),
        migrations.AddField(
            model_name='wfmodule',
            name='workflow',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='server.Workflow'),
            preserve_default=False,
        ),
    ]
