# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-08 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_clear_empty_colnames_from_cache'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicateTabCommand',
            fields=[
                ('delta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='server.Delta')),
                ('old_selected_tab_position', models.IntegerField()),
                ('tab', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='server.Tab')),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
            bases=('server.delta',),
        ),
        migrations.AlterModelOptions(
            name='delta',
            options={},
        ),
        migrations.AlterModelManagers(
            name='addmodulecommand',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='addtabcommand',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='changedataversioncommand',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='changeparameterscommand',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='changewfmodulenotescommand',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='changeworkflowtitlecommand',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='deletemodulecommand',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='deletetabcommand',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='delta',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='initworkflowcommand',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='reordermodulescommand',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='reordertabscommand',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='settabnamecommand',
            managers=[
            ],
        ),
    ]
