# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-27 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    """
    Fix https://www.pivotaltracker.com/story/show/166259286

	Previously, `.auto_update_data` and `.next_update` could get out of sync.
    That meant scheduled fetches weren't happening, or fetches were scheduled
    that can never happen.

    The fix:

    1. Set .next_update to NULL when `.auto_update_data` is NULL. (This
       paves the way for deleting `.auto_update_data` entirely.)
    2. Set .next_update when `.auto_update_data` IS NOT NULL.
    3. [TODO] nix .auto_update_data -- no more inconsistent records!
    """

    dependencies = [
        ('server', '0007_auto_20190508_1752'),
    ]

    operations = [
        migrations.RunSQL([
            """
            UPDATE server_wfmodule
            SET next_update = NULL
            WHERE NOT auto_update_data
            """,
            """
            UPDATE server_wfmodule
            SET next_update = NOW()
            WHERE auto_update_data AND next_update IS NULL
            """
        ], elidable=True),
    ]
