# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-23 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("server", "0007_auto_20190508_1752")]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        )
    ]
