# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_auto_20161129_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameterspec',
            name='default',
        ),
        migrations.RemoveField(
            model_name='parameterval',
            name='type',
        ),
        migrations.RemoveField(
            model_name='wfmodule',
            name='parameters',
        ),
        migrations.AddField(
            model_name='parameterspec',
            name='default_number',
            field=models.FloatField(blank=True, null=True, verbose_name='number'),
        ),
        migrations.AddField(
            model_name='parameterspec',
            name='default_string',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='string'),
        ),
        migrations.AddField(
            model_name='parameterspec',
            name='default_text',
            field=models.TextField(blank=True, null=True, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='parameterspec',
            name='type',
            field=models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('text', 'Text')], default='number', max_length=8),
        ),
        migrations.AddField(
            model_name='parameterval',
            name='parameter_spec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameter_vals', to='server.ParameterSpec'),
        ),
        migrations.AddField(
            model_name='parameterval',
            name='wf_module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameter_vals', to='server.WfModule'),
        ),
        migrations.AlterField(
            model_name='wfmodule',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wf_modules', to='server.Module'),
        ),
        migrations.AlterField(
            model_name='wfmodule',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wf_modules', to='server.Workflow'),
        ),
    ]
