# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-15 00:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_auto_20161213_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameterspec',
            old_name='default_number',
            new_name='def_number',
        ),
        migrations.RenameField(
            model_name='parameterspec',
            old_name='default_string',
            new_name='def_string',
        ),
        migrations.RenameField(
            model_name='parameterspec',
            old_name='default_text',
            new_name='def_text',
        ),
    ]
