# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-27 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_settabnamecommand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameterval',
            name='visible',
        ),
    ]
