# Generated by Django 2.2.16 on 2020-10-01 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("server", "0009_remove_wfmodule_fetch_error"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ChangeWfModuleNotesCommand",
            new_name="ChangeStepNotesCommand",
        ),
        migrations.RenameField(
            model_name="addmodulecommand",
            old_name="wf_module_delta_ids",
            new_name="step_delta_ids",
        ),
        migrations.RenameField(
            model_name="changedataversioncommand",
            old_name="wf_module_delta_ids",
            new_name="step_delta_ids",
        ),
        migrations.RenameField(
            model_name="changeparameterscommand",
            old_name="wf_module_delta_ids",
            new_name="step_delta_ids",
        ),
        migrations.RenameField(
            model_name="deletemodulecommand",
            old_name="wf_module_delta_ids",
            new_name="step_delta_ids",
        ),
        migrations.RenameField(
            model_name="inprogressupload",
            old_name="wf_module",
            new_name="step",
        ),
        migrations.RenameField(
            model_name="reordermodulescommand",
            old_name="wf_module_delta_ids",
            new_name="step_delta_ids",
        ),
        migrations.RenameField(
            model_name="reordertabscommand",
            old_name="wf_module_delta_ids",
            new_name="step_delta_ids",
        ),
        migrations.RenameField(
            model_name="settabnamecommand",
            old_name="wf_module_delta_ids",
            new_name="step_delta_ids",
        ),
        migrations.RenameField(
            model_name="storedobject",
            old_name="wf_module",
            new_name="step",
        ),
        migrations.RenameField(
            model_name="tab",
            old_name="selected_wf_module_position",
            new_name="selected_step_position",
        ),
        migrations.RenameField(
            model_name="uploadedfile",
            old_name="wf_module",
            new_name="step",
        ),
        migrations.AlterField(
            model_name="wfmodule",
            name="tab",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="steps",
                to="server.Tab",
            ),
        ),
    ]
