# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-27 16:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_remove_parameterval_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameterspec',
            name='def_visible',
        ),
        migrations.RemoveField(
            model_name='parameterspec',
            name='ui_only',
        ),
    ]
