# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-30 21:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_auto_20190528_1352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadedfile',
            options={'ordering': ['-created_at']},
        ),
    ]
