# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-31 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0008_schedule_orphan_fetches"),
        ("server", "0011_auto_20190530_2132"),
    ]

    operations = []
