# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-27 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_auto_20181227_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameterspec',
            old_name='def_items',
            new_name='items',
        ),
        migrations.RemoveField(
            model_name='parameterval',
            name='items',
        ),
    ]
