# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-21 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_auto_20170109_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='revision',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='workflow',
            name='revision_date',
            field=models.DateTimeField(auto_now_add=True, default='2000-01-01T12:00Z'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parameterspec',
            name='type',
            field=models.CharField(choices=[('String', 'String'), ('Number', 'Number'), ('Text', 'Text')], default='Number', max_length=8),
        ),
    ]
