# Generated by Django 2.2.16 on 2020-10-01 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0011_auto_20201001_1732"),
    ]

    operations = [
        migrations.RenameField(
            model_name="addmodulecommand",
            old_name="wf_module",
            new_name="step",
        ),
        migrations.RenameField(
            model_name="changedataversioncommand",
            old_name="wf_module",
            new_name="step",
        ),
        migrations.RenameField(
            model_name="changeparameterscommand",
            old_name="wf_module",
            new_name="step",
        ),
        migrations.RenameField(
            model_name="changestepnotescommand",
            old_name="wf_module",
            new_name="step",
        ),
        migrations.RenameField(
            model_name="deletemodulecommand",
            old_name="wf_module",
            new_name="step",
        ),
    ]
