# Generated by Django 2.2.16 on 2020-10-01 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0012_auto_20201001_1734"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="changestepnotescommand",
            table="server_changestepnotescommand",
        ),
    ]
