# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_auto_20170121_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='wfmodule',
            name='errormsg',
            field=models.CharField(blank=True, max_length=200, verbose_name='errormsg'),
        ),
        migrations.AddField(
            model_name='wfmodule',
            name='status',
            field=models.CharField(choices=[('ready', 'Ready'), ('busy', 'Busy'), ('error', 'Error')], default='ready', max_length=8),
        ),
        migrations.AlterField(
            model_name='parameterspec',
            name='type',
            field=models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('text', 'Text')], default='number', max_length=8),
        ),
    ]
