# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-27 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_auto_20181227_1720'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parameterval',
            options={'ordering': ['parameter_spec__order']},
        ),
        migrations.RemoveField(
            model_name='parameterval',
            name='order',
        ),
    ]
