# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-28 15:31
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_auto_20181227_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='wfmodule',
            name='params',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='wfmodule',
            name='secrets',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
