# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_auto_20170127_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wfmodule',
            name='errormsg',
        ),
        migrations.AddField(
            model_name='wfmodule',
            name='error_msg',
            field=models.CharField(blank=True, max_length=200, verbose_name='error_msg'),
        ),
    ]
