# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-28 20:54
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_auto_20181228_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameterval',
            name='parameter_spec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.ParameterSpec'),
        ),
        migrations.AlterField(
            model_name='wfmodule',
            name='params',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, null=True),
        ),
        migrations.AlterField(
            model_name='wfmodule',
            name='secrets',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, null=True),
        ),
    ]
