# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_auto_20170127_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='internal_name',
            new_name='id_name',
        ),
        migrations.AddField(
            model_name='parameterspec',
            name='id_name',
            field=models.CharField(default='', max_length=32, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parameterspec',
            name='name',
            field=models.CharField(max_length=64, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='parameterspec',
            name='type',
            field=models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('text', 'Text'), ('button', 'Button')], default='number', max_length=8),
        ),
    ]
