# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-28 20:55
from __future__ import unicode_literals

from django.db import migrations


def move_secrets_to_wf_module(apps, schema_editor):
    import json
    import sys
    WfModule = apps.get_model('server', 'WfModule')
    ParameterVal = apps.get_model('server', 'ParameterVal')

    for wf_module in (
        WfModule.objects.exclude(secrets__isnull=False)
    ):
        try:
            wf_module.refresh_from_db()
        except WfModule.DoesNotExist:
            sys.stdout.write('WfModule %d was deleted\n' % wf_module.id)
        if wf_module.secrets is not None:
            sys.stdout.write('WfModule %d already has .secrets\n' %
                             wf_module.id)

        secrets = {}
        parameter_vals = ParameterVal.objects.filter(
            parameter_spec__type='secret',
            wf_module_id=wf_module.id
        ).select_related('parameter_spec')

        for pv in parameter_vals.all():
            secret = pv.value
            if secret:
                secret = json.loads(secret)
                secrets[pv.parameter_spec.id_name] = secret

        wf_module.secrets = secrets
        wf_module.save(update_fields=['secrets'])
        if secrets:
            parameter_vals.delete()  # (just the secrets)


class Migration(migrations.Migration):
    """
    Migrate all secrets out of server_parameterval into server_wfmodule.

    The new column, server_wfmodule.secrets, is a JSON column keyed by service.
    (Currently, no module has more than one secret.) Once this migration
    completes, there will be no SECRET in server_parametervals. And since we
    have no code that _writes_ SECRETs to server_parametervals, the end result
    is that wf_module.secrets will never be NULL.

    See https://www.pivotaltracker.com/story/show/162704659
    """
    dependencies = [
        ('server', '0015_auto_20181228_2054'),
    ]

    operations = [
        migrations.RunPython(move_secrets_to_wf_module, elidable=True,
                             atomic=False),
        # Delete secrets that were obsolete -- as in, wf_module.secrets was not
        # NULL prior to migration.
        #
        # This happens when users modify their secrets prior to the migration:
        # the code we've deployed writes new values to wf_module.secrets
        # without deleting obsolete secrets. We _definitely_ want to delete
        # these secrets, since the user didn't mean for us to keep them!
        migrations.RunSQL([
            """
            DELETE FROM server_parameterval WHERE parameter_spec_id IN (
                SELECT id FROM server_parameterspec WHERE type = 'secret'
            )
            """
        ], elidable=True),
    ]
