# Generated by Django 2.2.2 on 2019-06-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("server", "0015_auto_20190603_1422")]

    operations = [
        migrations.AlterField(
            model_name="wfmodule",
            name="inprogress_file_upload_id",
            field=models.CharField(
                blank=True, default=None, max_length=255, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="wfmodule",
            name="inprogress_file_upload_key",
            field=models.CharField(
                blank=True, default=None, max_length=100, null=True, unique=True
            ),
        ),
        migrations.AddConstraint(
            model_name="wfmodule",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("inprogress_file_upload_id__isnull", True),
                        ("inprogress_file_upload_key__isnull", True),
                        ("inprogress_file_upload_last_accessed_at__isnull", True),
                    ),
                    models.Q(
                        ("inprogress_file_upload_id__isnull", False),
                        ("inprogress_file_upload_key__isnull", False),
                        ("inprogress_file_upload_last_accessed_at__isnull", False),
                    ),
                    models.Q(
                        ("inprogress_file_upload_id__isnull", True),
                        ("inprogress_file_upload_key__isnull", False),
                        ("inprogress_file_upload_last_accessed_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="inprogress_file_upload_check",
            ),
        ),
    ]
