# Generated by Django 2.2.16 on 2020-10-19 20:51

import cjwstate.models.commands.util
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0015_auto_20201019_1926"),
    ]

    operations = [
        migrations.AddField(
            model_name="delta",
            name="migrate_step",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="server.Step"
            ),
        ),
        migrations.AddField(
            model_name="delta",
            name="migrate_step_delta_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.IntegerField(), size=2
                ),
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="delta",
            name="migrate_tab",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="server.Tab"
            ),
        ),
        migrations.AddField(
            model_name="delta",
            name="values_for_backward",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="delta",
            name="values_for_forward",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
