# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0015_auto_20170128_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='id_name',
            field=models.CharField(max_length=200, verbose_name='id_name'),
        ),
    ]
