# Generated by Django 2.2.16 on 2020-10-19 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0016_auto_20201019_2051"),
    ]

    operations = [
        migrations.RunSQL(
            [
                """
                UPDATE delta
                SET
                    values_for_backward = json_build_object('old_selected_tab_position', x.old_selected_tab_position),
                    migrate_tab_id = x.tab_id
                FROM server_addtabcommand x
                WHERE x.delta_ptr_id = delta.id
                """,
                """
                UPDATE delta
                SET migrate_tab_id = x.tab_id
                FROM server_deletetabcommand x
                WHERE x.delta_ptr_id = delta.id
                """,
                """
                UPDATE delta
                SET
                    migrate_step_id = x.step_id,
                    migrate_step_delta_ids = x.step_delta_ids
                FROM server_addmodulecommand x
                WHERE x.delta_ptr_id = delta.id
                """,
                """
                UPDATE delta
                SET
                    migrate_step_id = x.step_id,
                    migrate_step_delta_ids = x.step_delta_ids
                FROM server_deletemodulecommand x
                WHERE x.delta_ptr_id = delta.id
                """,
                """
                UPDATE delta
                SET
                    values_for_backward = json_build_object('old_selected_tab_position', x.old_selected_tab_position),
                    migrate_tab_id = x.tab_id
                FROM server_duplicatetabcommand x
                WHERE x.delta_ptr_id = delta.id
                """,
                """
                UPDATE delta
                SET
                    values_for_backward = json_build_object('legacy_format', x.old_order::jsonb),
                    values_for_forward = json_build_object('legacy_format', x.new_order::jsonb),
                    migrate_tab_id = x.tab_id,
                    migrate_step_delta_ids = x.step_delta_ids
                FROM server_reordermodulescommand x
                WHERE x.delta_ptr_id = delta.id
                """,
                """
                UPDATE delta
                SET
                    values_for_backward = json_build_object('tab_ids', x.old_order),
                    values_for_forward = json_build_object('tab_ids', x.new_order),
                    migrate_step_delta_ids = x.step_delta_ids
                FROM server_reordertabscommand x
                WHERE x.delta_ptr_id = delta.id
                """,
                """
                UPDATE delta
                SET
                    values_for_backward = json_build_object('name', x.old_name),
                    values_for_forward = json_build_object('name', x.new_name),
                    migrate_tab_id = x.tab_id,
                    migrate_step_delta_ids = x.step_delta_ids
                FROM server_settabnamecommand x
                WHERE x.delta_ptr_id = delta.id
                """,
                """
                UPDATE delta
                SET
                    values_for_backward = json_build_object('version', x.old_version),
                    values_for_forward = json_build_object('version', x.new_version),
                    migrate_step_id = x.step_id,
                    migrate_step_delta_ids = x.step_delta_ids
                FROM server_changedataversioncommand x
                WHERE x.delta_ptr_id = delta.id
                """,
                """
                UPDATE delta
                SET
                    values_for_backward = json_build_object('params', x.old_values),
                    values_for_forward = json_build_object('params', x.new_values),
                    migrate_step_id = x.step_id,
                    migrate_step_delta_ids = x.step_delta_ids
                FROM server_changeparameterscommand x
                WHERE x.delta_ptr_id = delta.id
                """,
                """
                UPDATE delta
                SET
                    values_for_backward = json_build_object('note', x.old_value),
                    values_for_forward = json_build_object('note', x.new_value),
                    migrate_step_id = x.step_id
                FROM server_changestepnotescommand x
                WHERE x.delta_ptr_id = delta.id
                """,
                """
                UPDATE delta
                SET
                    values_for_backward = json_build_object('title', x.old_value),
                    values_for_forward = json_build_object('title', x.new_value)
                FROM server_changeworkflowtitlecommand x
                WHERE x.delta_ptr_id = delta.id
                """,
            ],
            elidable=True,
        )
    ]
