# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0016_auto_20170128_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameterspec',
            name='def_number',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='parameterspec',
            name='def_string',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='string'),
        ),
        migrations.AlterField(
            model_name='parameterspec',
            name='def_text',
            field=models.TextField(blank=True, default='', verbose_name='text'),
        ),
    ]
