# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0017_auto_20170130_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, default='', max_length=64, verbose_name='key')),
                ('text', models.TextField(blank=True, default='', verbose_name='text')),
                ('stored_at', models.DateTimeField(auto_now=True, verbose_name='stored_at')),
                ('wf_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wf_module', to='server.WfModule')),
            ],
        ),
    ]
