# Generated by Django 2.2.16 on 2020-10-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0018_auto_20201019_2203"),
    ]

    operations = [
        migrations.AddField(
            model_name="delta",
            name="command_name",
            field=models.CharField(
                choices=[
                    ("AddStep", "AddStep"),
                    ("AddTab", "AddTab"),
                    ("DeleteStep", "DeleteStep"),
                    ("DeleteTab", "DeleteTab"),
                    ("DuplicateTab", "DuplicateTab"),
                    ("InitWorkflow", "InitWorkflow"),
                    ("ReorderSteps", "ReorderSteps"),
                    ("ReorderTabs", "ReorderTabs"),
                    ("SetStepDataVersion", "SetStepDataVersion"),
                    ("SetStepNote", "SetStepNote"),
                    ("SetStepParams", "SetStepParams"),
                    ("SetTabName", "SetTabName"),
                    ("SetWorkflowTitle", "SetWorkflowTitle"),
                ],
                default="",
                max_length=18,
            ),
            preserve_default=False,
        ),
    ]
