# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-28 22:57
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0018_move_params_to_wf_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wfmodule',
            name='params',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
