# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0018_storedobject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parameterspec',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='parameterval',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='parameterspec',
            name='order',
            field=models.IntegerField(default=0, verbose_name='order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parameterval',
            name='order',
            field=models.IntegerField(default=0, verbose_name='order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parameterspec',
            name='id_name',
            field=models.CharField(max_length=32, verbose_name='id_name'),
        ),
        migrations.AlterField(
            model_name='parameterspec',
            name='type',
            field=models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('text', 'Text'), ('button', 'Button'), ('custom', 'Custom')], default='number', max_length=8),
        ),
    ]
