# Generated by Django 2.2.2 on 2019-06-18 16:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("server", "0018_fix_upload_stored_data_version")]

    operations = [
        migrations.AddField(
            model_name="workflow",
            name="last_viewed_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        )
    ]
