# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0019_auto_20170208_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storedobject',
            name='text',
        ),
        migrations.AddField(
            model_name='storedobject',
            name='data',
            field=models.BinaryField(blank=True),
        ),
        migrations.AlterField(
            model_name='parameterspec',
            name='order',
            field=models.IntegerField(default=0, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='parameterval',
            name='order',
            field=models.IntegerField(default=0, verbose_name='order'),
        ),
    ]
