# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-28 23:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0019_auto_20181228_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameterval',
            name='parameter_spec',
        ),
        migrations.RemoveField(
            model_name='parameterval',
            name='wf_module',
        ),
        migrations.DeleteModel(
            name='ParameterVal',
        ),
    ]
