# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0020_auto_20170208_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterspec',
            name='def_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parameterval',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
