# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-31 15:03
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import server.models.module_version


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0020_auto_20181228_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleversion',
            name='spec',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True, validators=[server.models.module_version.validate_module_spec], verbose_name='spec'),
        ),
    ]
