# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-01 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0021_moduleversion_spec'),
    ]

    operations = [
        migrations.AddField(
            model_name='wfmodule',
            name='module_id_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
