# Generated by Django 2.2.16 on 2020-10-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0021_auto_20201020_1903"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="delta",
            constraint=models.CheckConstraint(
                check=models.Q(
                    command_name__in=[
                        "AddStep",
                        "AddTab",
                        "DeleteStep",
                        "DeleteTab",
                        "DuplicateTab",
                        "InitWorkflow",
                        "ReorderSteps",
                        "ReorderTabs",
                        "SetStepDataVersion",
                        "SetStepNote",
                        "SetStepParams",
                        "SetTabName",
                        "SetWorkflowTitle",
                    ]
                ),
                name="delta_command_name_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="delta",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("command_name", "InitWorkflow"),
                        ("prev_delta_id__isnull", True),
                    ),
                    models.Q(
                        models.Q(_negated=True, command_name="InitWorkflow"),
                        ("prev_delta_id__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="delta_first_command_per_workflow_is_init",
            ),
        ),
    ]
