# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 02:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server', '0022_auto_20170223_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parameterval',
            name='ui_only',
            field=models.BooleanField(default=False),
        ),
    ]
