# Generated by Django 2.2.2 on 2019-06-18 18:42

from django.db import migrations


class Migration(migrations.Migration):
    """
    One-shot: bump max_fetches_per_day for our luckiest users.

    This relates to https://www.pivotaltracker.com/story/show/166747713. We're
    adding a limit on number of fetches per day, but we don't want to affect
    existing users (as part of this bug). So let's increase our problem users'
    limits for now; afterwards we can negotiate with them and move the limits
    back down.
    """

    dependencies = [
        ('cjworkbench', '0002_userprofile_max_fetches_per_day'),
        ('server', '0022_auto_20190618_1803'),
    ]

    operations = [
        migrations.RunSQL([
            """
            UPDATE cjworkbench_userprofile
            SET max_fetches_per_day = (
                SELECT GREATEST(
                    500,
                    CEIL(SUM(86400.0/GREATEST(300, update_interval)))
                )
                FROM server_wfmodule
                INNER JOIN server_tab
                        ON server_wfmodule.tab_id = server_tab.id
                       AND NOT server_tab.is_deleted
                INNER JOIN server_workflow
                        ON server_tab.workflow_id = server_workflow.id
                WHERE server_wfmodule.auto_update_data
                  AND NOT server_wfmodule.is_deleted
                  AND server_workflow.owner_id = cjworkbench_userprofile.user_id
            )
            """
        ], elidable=True)
    ]
