# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-01 22:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    """
    Fill wf_module.module_id_name everywhere.

    In cases where we've already lost the user's information (by setting
    module_version_id = NULL), write module_id_name='', which means 'deleted'.
    """

    dependencies = [
        ('server', '0022_wfmodule_module_id_name'),
    ]

    operations = [
        migrations.RunSQL([
            """
            UPDATE server_wfmodule
            SET module_id_name = COALESCE(
                (SELECT id_name
                 FROM server_module
                 WHERE id = (
                    SELECT module_id
                    FROM server_moduleversion
                    WHERE id = server_wfmodule.module_version_id
                 )
                ),
                ''
            )
            """
        ], elidable=True)
    ]
