# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-01 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0023_wf_module_module_id_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wfmodule',
            name='module_version',
        ),
        migrations.AlterField(
            model_name='wfmodule',
            name='module_id_name',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
