# Generated by Django 2.2.16 on 2020-11-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0023_auto_20201102_2104"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="delta",
            name="delta_command_name_valid",
        ),
        migrations.AlterField(
            model_name="delta",
            name="command_name",
            field=models.CharField(
                choices=[
                    ("AddBlock", "AddBlock"),
                    ("AddStep", "AddStep"),
                    ("AddTab", "AddTab"),
                    ("DeleteBlock", "DeleteBlock"),
                    ("DeleteStep", "DeleteStep"),
                    ("DeleteTab", "DeleteTab"),
                    ("DuplicateTab", "DuplicateTab"),
                    ("InitWorkflow", "InitWorkflow"),
                    ("ReorderBlocks", "ReorderBlocks"),
                    ("ReorderSteps", "ReorderSteps"),
                    ("ReorderTabs", "ReorderTabs"),
                    ("SetBlockMarkdown", "SetBlockMarkdown"),
                    ("SetStepDataVersion", "SetStepDataVersion"),
                    ("SetStepNote", "SetStepNote"),
                    ("SetStepParams", "SetStepParams"),
                    ("SetTabName", "SetTabName"),
                    ("SetWorkflowTitle", "SetWorkflowTitle"),
                ],
                max_length=18,
            ),
        ),
        migrations.AddConstraint(
            model_name="delta",
            constraint=models.CheckConstraint(
                check=models.Q(
                    command_name__in=[
                        "AddBlock",
                        "AddStep",
                        "AddTab",
                        "DeleteBlock",
                        "DeleteStep",
                        "DeleteTab",
                        "DuplicateTab",
                        "InitWorkflow",
                        "ReorderBlocks",
                        "ReorderSteps",
                        "ReorderTabs",
                        "SetBlockMarkdown",
                        "SetStepDataVersion",
                        "SetStepNote",
                        "SetStepParams",
                        "SetTabName",
                        "SetWorkflowTitle",
                    ]
                ),
                name="delta_command_name_valid",
            ),
        ),
    ]
