# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-04-08 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0023_auto_20170227_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterspec',
            name='def_checkbox',
            field=models.BooleanField(default=True, verbose_name='checkbox'),
        ),
        migrations.AddField(
            model_name='parameterval',
            name='checkbox',
            field=models.BooleanField(default=True, verbose_name='checkbox'),
        ),
        migrations.AlterField(
            model_name='parameterspec',
            name='type',
            field=models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('text', 'Text'), ('button', 'Button'), ('checkbox', 'Checkbox'), ('custom', 'Custom')], default='number', max_length=8),
        ),
    ]
