# Generated by Django 2.2.3 on 2019-07-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("server", "0024_remove_storedobject_metadata")]

    operations = [
        migrations.AddField(
            model_name="wfmodule",
            name="file_upload_api_token",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        )
    ]
