# Generated by Django 3.1.5 on 2021-01-13 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0025_enforce_storage_limits"),
    ]

    operations = [
        migrations.RunSQL(
            [
                """
                UPDATE workflow
                SET has_custom_report = TRUE
                WHERE id IN (SELECT DISTINCT workflow_id FROM block)
                """
            ],
            elidable=True,
        )
    ]
