# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0025_auto_20170426_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameterspec',
            name='def_text',
        ),
        migrations.RemoveField(
            model_name='parameterval',
            name='text',
        ),
        migrations.AddField(
            model_name='parameterspec',
            name='def_multiline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parameterval',
            name='multiline',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parameterspec',
            name='def_string',
            field=models.TextField(blank=True, default='', verbose_name='string'),
        ),
        migrations.AlterField(
            model_name='parameterspec',
            name='type',
            field=models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('button', 'Button'), ('checkbox', 'Checkbox'), ('custom', 'Custom')], default='number', max_length=8),
        ),
        migrations.AlterField(
            model_name='parameterval',
            name='string',
            field=models.TextField(blank=True, null=True, verbose_name='string'),
        ),
    ]
