# Generated by Django 2.2.3 on 2019-07-24 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("server", "0025_wfmodule_file_upload_api_token")]

    operations = [
        migrations.AlterField(
            model_name="tab", name="slug", field=models.SlugField(db_index=False)
        )
    ]
