# Generated by Django 2.2.3 on 2019-07-24 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("server", "0026_auto_20190724_2358")]

    operations = [
        migrations.AddField(
            model_name="wfmodule", name="slug", field=models.SlugField(null=True)
        )
    ]
