# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-02 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0026_auto_20190102_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleversion',
            name='id_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='moduleversion',
            name='last_update_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='moduleversion',
            name='source_version_hash',
            field=models.CharField(default='1.0', max_length=200),
        ),
    ]
