# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0026_auto_20170504_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterspec',
            name='def_menu_items',
            field=models.TextField(blank=True, null=True, verbose_name='menu'),
        ),
        migrations.AddField(
            model_name='parameterspec',
            name='def_menu_selected',
            field=models.IntegerField(blank=True, default='0', verbose_name='menu_selected'),
        ),
        migrations.AddField(
            model_name='parameterval',
            name='menu_items',
            field=models.TextField(blank=True, null=True, verbose_name='menu'),
        ),
        migrations.AddField(
            model_name='parameterval',
            name='menu_selected',
            field=models.IntegerField(blank=True, default='0', verbose_name='menu_selected'),
        ),
        migrations.AlterField(
            model_name='parameterspec',
            name='type',
            field=models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('button', 'Button'), ('checkbox', 'Checkbox'), ('menu', 'Menu'), ('custom', 'Custom')], default='number', max_length=8),
        ),
    ]
