# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-02 15:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0027_auto_20190102_1516'),
    ]

    operations = [
        migrations.RunSQL([
            """
            UPDATE server_moduleversion
            SET id_name = spec -> 'id_name'
            """,
            """
            UPDATE server_moduleversion
            SET last_update_time = NOW()
            WHERE last_update_time IS NULL
            """
        ], elidable=True)
    ]
