# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0027_auto_20170515_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameterspec',
            name='def_checkbox',
        ),
        migrations.RemoveField(
            model_name='parameterspec',
            name='def_menu_selected',
        ),
        migrations.RemoveField(
            model_name='parameterspec',
            name='def_number',
        ),
        migrations.RemoveField(
            model_name='parameterval',
            name='checkbox',
        ),
        migrations.RemoveField(
            model_name='parameterval',
            name='menu_selected',
        ),
        migrations.RemoveField(
            model_name='parameterval',
            name='number',
        ),
        migrations.AddField(
            model_name='parameterspec',
            name='def_boolean',
            field=models.NullBooleanField(default=True, verbose_name='boolean'),
        ),
        migrations.AddField(
            model_name='parameterspec',
            name='def_float',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='float'),
        ),
        migrations.AddField(
            model_name='parameterspec',
            name='def_integer',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='integer'),
        ),
        migrations.AddField(
            model_name='parameterval',
            name='boolean',
            field=models.BooleanField(default=True, verbose_name='boolean'),
        ),
        migrations.AddField(
            model_name='parameterval',
            name='float',
            field=models.FloatField(blank=True, null=True, verbose_name='float'),
        ),
        migrations.AddField(
            model_name='parameterval',
            name='integer',
            field=models.IntegerField(blank=True, default='0', verbose_name='integer'),
        ),
        migrations.AlterField(
            model_name='parameterspec',
            name='def_string',
            field=models.TextField(blank=True, default='', null=True, verbose_name='string'),
        ),
    ]
