# Generated by Django 2.2.3 on 2019-07-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("server", "0027_wfmodule_slug")]

    operations = [
        migrations.AlterField(
            model_name="wfmodule",
            name="inprogress_file_upload_id",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        )
    ]
