# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-02 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0028_module_version_no_nulls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleversion',
            name='id_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='moduleversion',
            name='last_update_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='moduleversion',
            unique_together=set([('id_name', 'last_update_time')]),
        ),
    ]
