# Generated by Django 3.1.5 on 2021-01-29 16:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0028_delete_inprogressupload"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflow",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="last_delta",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="server.delta",
            ),
        ),
        migrations.RunSQL(
            [
                """
                UPDATE workflow
                SET updated_at = (
                    SELECT "datetime" FROM delta WHERE delta.id = workflow.last_delta_id
                )
                """
            ],
            elidable=True,
        ),
    ]
