# Generated by Django 2.2.3 on 2019-07-28 14:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [("server", "0029_auto_20190727_2107")]

    operations = [
        migrations.CreateModel(
            name="InProgressUpload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "wf_module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_progress_uploads",
                        to="server.WfModule",
                    ),
                ),
            ],
        )
    ]
