# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-22 04:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0029_auto_20170621_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wfmodule',
            old_name='module',
            new_name='module_version',
        ),
    ]
