# Generated by Django 3.1.6 on 2021-02-01 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0029_auto_20210129_1644"),
    ]

    operations = [
        migrations.AddField(
            model_name="delta",
            name="last_applied_at",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="aclentry",
            name="created_at",
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name="delta",
            name="datetime",
            field=models.DateTimeField(
                default=datetime.datetime.now, verbose_name="datetime"
            ),
        ),
        migrations.AlterField(
            model_name="storedobject",
            name="stored_at",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="created_at",
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="last_viewed_at",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="updated_at",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
