# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-23 03:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0030_auto_20170622_0420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameterspec',
            name='module',
        ),
        migrations.AddField(
            model_name='parameterspec',
            name='module_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameter_specs', to='server.ModuleVersion'),
        ),
    ]
