# Generated by Django 2.2.3 on 2019-07-29 02:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("server", "0030_inprogressupload")]

    operations = [
        migrations.AlterField(
            model_name="inprogressupload",
            name="updated_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        )
    ]
