# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-02 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0030_moduleversion_js_module'),
    ]

    operations = [
        migrations.RunSQL([
            """
            UPDATE server_moduleversion
            SET js_module = (
                SELECT js_module
                FROM server_module
                WHERE server_module.id = server_moduleversion.module_id
            )
            """
        ], elidable=True)
    ]
