# Generated by Django 3.1.6 on 2021-02-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0031_impute_delta_last_applied_at"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="delta",
            name="delta_first_command_per_workflow_is_init",
        ),
        migrations.RunSQL(
            # Change from a foreign-key column to an integer column, without
            # Django noticing
            [
                # [2021-02-01, adamhooper] I found the constraint name by
                # looking at existing dev+prod databases. (It's the same on both.)
                """
                ALTER TABLE workflow
                DROP CONSTRAINT workflow_last_delta_id_ba1a9114_fk_delta_id
                """
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name="workflow",
                    name="last_delta",
                ),
                migrations.AddField(
                    model_name="workflow",
                    name="last_delta_id",
                    field=models.IntegerField(default=0),
                ),
            ],
        ),
    ]
