# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-23 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0031_auto_20170623_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleversion',
            name='last_update_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='last_update_time'),
        ),
    ]
