# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-30 00:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0032_auto_20170623_0413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.IntegerField(default=1)),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='datetime')),
                ('command_description', models.CharField(max_length=200, verbose_name='command_description')),
            ],
        ),
        migrations.AlterField(
            model_name='wfmodule',
            name='workflow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wf_modules', to='server.Workflow'),
        ),
        migrations.CreateModel(
            name='AddModuleCommand',
            fields=[
                ('delta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='server.Delta')),
                ('order', models.IntegerField(verbose_name='order')),
                ('module_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.ModuleVersion')),
                ('wf_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.WfModule')),
            ],
            bases=('server.delta',),
        ),
        migrations.CreateModel(
            name='ChangeParameterCommand',
            fields=[
                ('delta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='server.Delta')),
                ('new_value', models.TextField(verbose_name='new_value')),
                ('old_value', models.TextField(verbose_name='old_value')),
                ('parameter_val', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.ParameterVal')),
            ],
            bases=('server.delta',),
        ),
        migrations.CreateModel(
            name='DeleteModuleCommand',
            fields=[
                ('delta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='server.Delta')),
                ('wf_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.WfModule')),
            ],
            bases=('server.delta',),
        ),
        migrations.AddField(
            model_name='delta',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='server.Workflow'),
        ),
    ]
