# Generated by Django 3.1.6 on 2021-02-02 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0032_auto_20210201_2122"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delta",
            name="last_applied_at",
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now),
        ),
    ]
