# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-02 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0032_auto_20190102_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moduleversion',
            name='module',
        ),
        migrations.AlterField(
            model_name='moduleversion',
            name='last_update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Module',
        ),
    ]
