# Generated by Django 3.1.6 on 2021-02-03 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0033_auto_20210202_1848"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delta",
            name="last_applied_at",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddIndex(
            model_name="delta",
            index=models.Index(
                fields=["workflow_id", "last_applied_at"],
                name="index_delta_for_stale_scan",
            ),
        ),
    ]
