# Generated by Django 2.2.3 on 2019-07-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("server", "0033_assign_wf_module_slugs")]

    operations = [
        migrations.AlterField(
            model_name="wfmodule", name="slug", field=models.SlugField()
        ),
        migrations.AddConstraint(
            model_name="wfmodule",
            constraint=models.UniqueConstraint(
                fields=("tab_id", "slug"), name="unique_wf_module_slug"
            ),
        ),
    ]
