# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-07 01:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0034_auto_20170706_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeDataVersionCommand',
            fields=[
                ('delta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='server.Delta')),
                ('old_version', models.TextField(verbose_name='old_version')),
                ('new_version', models.TextField(verbose_name='new_version')),
            ],
            bases=('server.delta',),
        ),
        migrations.AddField(
            model_name='wfmodule',
            name='stored_data_version',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='wfmodule',
            name='order',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='changedataversioncommand',
            name='wf_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.WfModule'),
        ),
    ]
