# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-03 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    """
    Make server_changeparameterscommand.new_values complete.

    The .old_values and .new_values may now apply to different module versions,
    so one can't be derived from the other. In the common case, we duplicate
    values -- indeed, that's what this migration does. In edge cases,
    .old_values and .new_values have different keys -- which we'll be able to
    implement once this migration is finished.

    Rephrased: pre-migration, .old_values is complete and .new_values is only
    the _changed_ values. Post-migration, .old_values and .new_values are both
    complete.
    """
    dependencies = [
        ('server', '0034_auto_20190102_2211'),
    ]

    operations = [
        migrations.RunSQL([
            """
            UPDATE server_changeparameterscommand
            SET new_values = old_values || new_values
            """
        ], elidable=True)
    ]
