# Generated by Django 3.1.6 on 2021-02-05 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0034_auto_20210203_1530"),
        ("server", "0034_delete_unique_index_on_workflow_duplicates"),
    ]

    operations = []
