# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-21 20:22
from __future__ import unicode_literals

from pathlib import Path
from django.db import migrations
from server import minio


def copy_module_code_to_s3(apps, schema_editor):
    ModuleVersion = apps.get_model('server', 'ModuleVersion')
    minio.ensure_bucket_exists(minio.ExternalModulesBucket)

    for mv in ModuleVersion.objects.all():
        code_path = (
            Path(__file__).parent.parent.parent  # .../cjworkbench
            / 'importedmodules'
            / mv.id_name
            / mv.source_version_hash
        )
        minio.fput_directory_contents(
            minio.ExternalModulesBucket,
            '%s/%s' % (mv.id_name, mv.source_version_hash),
            code_path
        )


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0035_changeparameterscommand_moduleversions'),
    ]

    operations = [
        migrations.RunPython(copy_module_code_to_s3, elidable=True),
    ]
