# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-07 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0035_auto_20170707_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delta',
            name='revision',
            field=models.IntegerField(),
        ),
    ]
