# Generated by Django 2.2.4 on 2019-09-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("server", "0036_wfmodule_cached_render_result_errors")]

    operations = [
        migrations.AlterField(
            model_name="wfmodule",
            name="fetch_error",
            field=models.CharField(
                blank=True, max_length=10000, verbose_name="fetch_error"
            ),
        )
    ]
