# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-14 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0037_reordermodulescommand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameterspec',
            old_name='def_multiline',
            new_name='multiline',
        ),
        migrations.RenameField(
            model_name='parameterspec',
            old_name='def_ui_only',
            new_name='ui_only',
        ),
        migrations.RemoveField(
            model_name='parameterval',
            name='multiline',
        ),
        migrations.RemoveField(
            model_name='parameterval',
            name='ui_only',
        ),
        migrations.AddField(
            model_name='parameterspec',
            name='derived_data',
            field=models.BooleanField(default=False),
        ),
    ]
