# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-24 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import server.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0037_wipe_cached_render_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='wfmodule',
            name='cached_render_result_columns',
            field=server.models.fields.ColumnsField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wfmodule',
            name='cached_render_result_nrows',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
