# Generated by Django 2.2.5 on 2019-09-26 12:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("server", "0037_auto_20190913_2006")]

    operations = [
        migrations.AddField(
            model_name="wfmodule",
            name="cached_migrated_params",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wfmodule",
            name="cached_migrated_params_module_version",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddConstraint(
            model_name="wfmodule",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("cached_migrated_params__isnull", True),
                        ("cached_migrated_params_module_version__isnull", True),
                    ),
                    models.Q(
                        ("cached_migrated_params__isnull", False),
                        ("cached_migrated_params_module_version__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="cached_migrated_params_consistency_check",
            ),
        ),
    ]
