# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-18 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0038_auto_20170714_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='wfmodule',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
