# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-18 23:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0039_wfmodule_notes'),
        ('server', '0039_auto_20170718_2300'),
    ]

    operations = [
    ]
