# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-19 00:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0040_merge_20170718_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeWorkflowTitleCommand',
            fields=[
                ('delta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='server.Delta')),
                ('new_value', models.TextField(verbose_name='new_value')),
                ('old_value', models.TextField(verbose_name='old_value')),
            ],
            bases=('server.delta',),
        ),
    ]
