# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-25 23:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0040_auto_20190124_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addmodulecommand',
            name='selected_wf_module_position',
        ),
    ]
