# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-28 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0041_remove_addmodulecommand_selected_wf_module_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='tab',
            name='slug',
            field=models.SlugField(db_index=False, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='tab',
            unique_together=set([('workflow', 'slug')]),
        ),
    ]
