# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-19 02:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('server', '0041_changeworkflowtitlecommand'),
    ]

    operations = [
        migrations.AddField(
            model_name='delta',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_server.delta_set+', to='contenttypes.ContentType'),
        ),
    ]
