# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-28 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0042_auto_20190128_1447'),
    ]

    operations = [
        migrations.RunSQL([
            """
            UPDATE server_tab
            SET slug = 'tab-' || id
            WHERE slug = '' OR slug IS NULL
            """
        ], elidable=True)
    ]
