# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-19 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0042_delta_polymorphic_ctype'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='description',
            field=models.CharField(default='', max_length=200, verbose_name='description'),
        ),
    ]
