# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-19 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0043_module_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='author',
            field=models.CharField(default='Workbench', max_length=200, verbose_name='author'),
        ),
        migrations.AddField(
            model_name='module',
            name='link',
            field=models.CharField(default='', max_length=200, verbose_name='link'),
        ),
    ]
