# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-08 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0043_populate_tab_slug'),
    ]

    operations = [
        migrations.RunSQL([
            """
            UPDATE server_wfmodule
            SET module_id_name = 'duplicatecolumns'
            WHERE module_id_name = 'duplicate-column'
            """,
            """
            UPDATE server_wfmodule
            SET module_id_name = 'renamecolumns'
            WHERE module_id_name = 'rename-columns'
            """,
            """
            UPDATE server_wfmodule
            SET module_id_name = 'reordercolumns'
            WHERE module_id_name = 'reorder-columns'
            """,
            """
            UPDATE server_wfmodule
            SET module_id_name = 'sort'
            WHERE module_id_name = 'sort-from-table'
            """,
        ], elidable=True)
    ]
