# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-20 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0044_auto_20170719_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeWfModuleNoteCommand',
            fields=[
                ('delta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='server.Delta')),
                ('new_value', models.TextField(verbose_name='new_value')),
                ('old_value', models.TextField(verbose_name='old_value')),
                ('wf_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.WfModule')),
            ],
            options={
                'abstract': False,
            },
            bases=('server.delta',),
        ),
    ]
