# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-12 16:22
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0046_settabnamecommand_wf_module_delta_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='reordertabscommand',
            name='wf_module_delta_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=2), default=list, size=None),
            preserve_default=False,
        ),
    ]
