# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-20 20:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0046_auto_20170720_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wfmodule',
            old_name='note',
            new_name='notes',
        ),
    ]
