# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-20 20:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0047_auto_20170720_2025'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChangeWfModuleNoteCommand',
            new_name='ChangeWfModuleNotesCommand',
        ),
    ]
