# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-18 21:15
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import server.models.module_version


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0047_reordertabscommand_wf_module_delta_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleversion',
            name='spec',
            field=django.contrib.postgres.fields.jsonb.JSONField(validators=[server.models.module_version._django_validate_module_spec], verbose_name='spec'),
        ),
    ]
