# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-25 00:56
from __future__ import unicode_literals
from django.db import migrations
from django.contrib.sites.models import Site
import sys


def load_data(apps, schema_editor):
    # we don't have the django_sites table when testing, so do nothing then
    if not sys.argv[1:2] == ['test']:
        one = Site.objects.all()[0]
<<<<<<< HEAD
        one.domain = 'workbenchdata.com'
        one.name = 'CJ Workbench'
||||||| merged common ancestors
        one.domain = 'cjworkbench.org'
        one.name = 'CJ Workbench'
=======
        one.domain = 'workbenchdata.com'
        one.name = 'Workbench'
>>>>>>> master
        one.save()


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0048_auto_20170720_2032'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]

