# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-26 01:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0051_auto_20170725_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeWfModuleUpdateSettingsCommand',
            fields=[
                ('delta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='server.Delta')),
                ('new_auto', models.BooleanField()),
                ('old_auto', models.BooleanField()),
                ('new_next_update', models.DateField(null=True)),
                ('old_next_update', models.DateField(null=True)),
                ('new_update_interval', models.IntegerField()),
                ('old_update_interval', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('server.delta',),
        ),
        migrations.AddField(
            model_name='wfmodule',
            name='auto_update_data',
            field=models.BooleanField(default='True'),
        ),
        migrations.AddField(
            model_name='wfmodule',
            name='last_update_check',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='wfmodule',
            name='next_update',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='wfmodule',
            name='update_interval',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='changewfmoduleupdatesettingscommand',
            name='wf_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.WfModule'),
        ),
    ]
