# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-27 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0052_auto_20170726_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wfmodule',
            name='last_update_check',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='wfmodule',
            name='next_update',
            field=models.DateTimeField(null=True),
        ),
    ]
