# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-30 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0053_auto_20170727_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wfmodule',
            name='last_update_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wfmodule',
            name='next_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wfmodule',
            name='stored_data_version',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
