# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-28 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0053_auto_20170727_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
