# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-31 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0054_changewfmodulecollapsedsettingcommand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wfmodule',
            name='is_collapsed',
            field=models.BooleanField(default=False),
        ),
    ]
