# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-31 02:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0055_auto_20170731_0158'),
        ('server', '0054_auto_20170730_0134'),
    ]

    operations = [
    ]
