# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-31 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0054_workflow_public'),
        ('server', '0056_merge_20170731_0227'),
    ]

    operations = [
    ]
