# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-01 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0057_merge_20170731_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wfmodule',
            name='auto_update_data',
            field=models.BooleanField(default='False'),
        ),
    ]
