# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-02 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0058_auto_20170801_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='icon',
            field=models.CharField(default='url', max_length=20, verbose_name='icon'),
        ),
    ]
