# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-03 03:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0059_module_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changewfmodulecollapsedsettingcommand',
            name='delta_ptr',
        ),
        migrations.RemoveField(
            model_name='changewfmodulecollapsedsettingcommand',
            name='wf_module',
        ),
        migrations.DeleteModel(
            name='ChangeWfModuleCollapsedSettingCommand',
        ),
    ]
