# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-07 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0060_auto_20170803_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delta',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='datetime'),
        ),
        migrations.AlterField(
            model_name='delta',
            name='next_delta',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='+', to='server.Delta'),
        ),
        migrations.AlterField(
            model_name='delta',
            name='prev_delta',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='+', to='server.Delta'),
        ),
    ]
