# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-28 06:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0062_auto_20170810_2339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delta',
            options={'base_manager_name': 'base_objects'},
        ),
        migrations.AlterModelManagers(
            name='addmodulecommand',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='changedataversioncommand',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='changeparametercommand',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='changewfmodulenotescommand',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='changewfmoduleupdatesettingscommand',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='changeworkflowtitlecommand',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='deletemodulecommand',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='delta',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='reordermodulescommand',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='addmodulecommand',
            name='module_version',
        ),
        migrations.AlterField(
            model_name='addmodulecommand',
            name='wf_module',
            field=models.ForeignKey(null=True, blank=True, default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='server.WfModule'),
        ),
        migrations.AlterField(
            model_name='changedataversioncommand',
            name='wf_module',
            field=models.ForeignKey(null=True, blank=True, default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='server.WfModule'),
        ),
        migrations.AlterField(
            model_name='changeparametercommand',
            name='parameter_val',
            field=models.ForeignKey(null=True, blank=True, default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='server.ParameterVal'),
        ),
        migrations.AlterField(
            model_name='changewfmodulenotescommand',
            name='wf_module',
            field=models.ForeignKey(null=True, blank=True, default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='server.WfModule'),
        ),
        migrations.AlterField(
            model_name='changewfmoduleupdatesettingscommand',
            name='wf_module',
            field=models.ForeignKey(null=True, blank=True, default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='server.WfModule'),
        ),
        migrations.AlterField(
            model_name='deletemodulecommand',
            name='wf_module',
            field=models.ForeignKey(null=True, blank=True, default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='server.WfModule'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='last_delta',
            field=models.ForeignKey(null=True, blank=True, default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='+', to='server.Delta'),
        ),
    ]
