# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-05 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0063_auto_20170828_0601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storedobject',
            name='data',
        ),
        migrations.RemoveField(
            model_name='storedobject',
            name='key',
        ),
        migrations.AddField(
            model_name='storedobject',
            name='file',
            field=models.FileField(default=None, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='changedataversioncommand',
            name='new_version',
            field=models.DateTimeField(verbose_name='new_version'),
        ),
        migrations.AlterField(
            model_name='changedataversioncommand',
            name='old_version',
            field=models.DateTimeField(null=True, verbose_name='old_version'),
        ),
        migrations.AlterField(
            model_name='wfmodule',
            name='stored_data_version',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
