# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-14 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0064_auto_20170905_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedobject',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
