# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-22 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0066_auto_20170914_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedobject',
            name='wf_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stored_objects', to='server.WfModule'),
        ),
    ]
