# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-26 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0067_auto_20170922_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedobject',
            name='stored_at',
            field=models.DateTimeField(verbose_name='stored_at'),
        ),
    ]
