# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-02 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0068_auto_20170926_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmodulecommand',
            name='applied',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='deletemodulecommand',
            name='applied',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='addmodulecommand',
            name='order',
            field=models.IntegerField(),
        ),
    ]
