# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-13 13:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0070_auto_20171012_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedobject',
            name='stored_at',
            field=models.DateTimeField(default=timezone.now(), verbose_name='stored_at'),
        ),
    ]
