# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-13 19:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0071_auto_20171013_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedobject',
            name='stored_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 13, 19, 42, 24, 101694, tzinfo=utc), verbose_name='stored_at'),
        ),
    ]
