# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-13 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0072_auto_20171013_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedobject',
            name='stored_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='stored_at'),
        ),
    ]
