# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-18 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0073_auto_20171013_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedobject',
            name='success',
            field=models.BooleanField(default=True),
        ),
    ]
