# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-18 22:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0074_storedobject_success'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storedobject',
            name='success',
        ),
    ]
