# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-24 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0076_auto_20171025_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameterspec',
            name='name',
            field=models.CharField(max_length=256, verbose_name='name'),
        ),
    ]
