# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-12 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0078_module_loads_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wfmodule',
            name='auto_update_data',
            field=models.BooleanField(default=False),
        ),
    ]
