# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-12 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0080_auto_20171213_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='wfmodule',
            name='notifications',
            field=models.BooleanField(default=False),
        ),
    ]
