# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-13 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
from server.models import StoredObject, WfModule

# Simplest migration: delete all previous StoredObjects. Will require "check now" on existing wf, or re-upload files
def migrate_files(apps, schema_editor):
    for so in StoredObject.objects.all():
        wfm = so.wf_module
        wfm.set_fetched_data_version(None)
        wfm.save()
        so.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('server', '0080_wfmodule_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedobject',
            name='hash',
            field=models.CharField(default='xxxxxxxx', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storedobject',
            name='metadata',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='storedobject',
            name='type',
            field=models.CharField(choices=[('UPLOADED_FILE', 'UPLOADED_FILE'), ('FETCHED_TABLE', 'FETCHED_TABLE'), ('CACHED_TABLE', 'CACHED_TABLE')], default='UNKNOWN', max_length=16),
        ),
        migrations.AlterField(
            model_name='storedobject',
            name='name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='storedobject',
            name='size',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='storedobject',
            name='stored_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='storedobject',
            name='uuid',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.RunPython(migrate_files, lambda apps, schema_editor: None)
        # lambda, scheme make reversing possible, a NOP
    ]
