# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0080_auto_20171213_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=200)),
                ('wf_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.WfModule')),
            ],
        ),
    ]
