# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-04 19:09
from __future__ import unicode_literals

from django.db import migrations, models

def set_existing_to_true(apps, schema_editor):
    stored_objects = apps.get_model('server', 'StoredObject')
    for obj in stored_objects.objects.all().iterator():
        obj.read = True
        obj.save()

def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0081_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedobject',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_existing_to_true, reverse_code=reverse)
    ]
