# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-17 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0083_auto_20180109_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='html_output',
            field=models.BooleanField(default=False, verbose_name='html_output'),
        ),
    ]
