# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0085_auto_20180122_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterspec',
            name='placeholder',
            field=models.TextField(blank=True, null=True),
        ),
    ]
