# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-30 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0087_auto_20180125_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='module_library_collapsed',
            field=models.BooleanField(default=False),
        ),
    ]
