# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-31 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0088_workflow_module_library_collapsed'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='help_url',
            field=models.URLField(default=False, verbose_name='help_url'),
        ),
        migrations.AlterField(
            model_name='module',
            name='link',
            field=models.URLField(default='', verbose_name='link'),
        ),
    ]
