# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-01 03:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0089_workflow_selected_wf_module'),
        ('server', '0089_auto_20180201_0043'),
    ]

    operations = [
    ]
