# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0091_auto_20180209_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletemodulecommand',
            name='selected_wf_module',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
