# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-22 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0092_deletemodulecommand_selected_wf_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterspec',
            name='visible_if',
            field=models.TextField(default='', verbose_name='visible_if'),
        ),
        migrations.AddField(
            model_name='parameterspec',
            name='visible_if_not',
            field=models.TextField(default='', verbose_name='visible_if_not'),
        ),
    ]
