# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-28 01:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0093_storedobject_to_uploadedfile'),
        ('server', '0093_auto_20180322_1822'),
    ]

    operations = [
    ]
