# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-28 02:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0094_merge_20180328_0159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameterspec',
            name='visible_if_not',
        ),
    ]
