# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-13 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0096_auto_20180411_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmodulecommand',
            name='selected_wf_module',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
