# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-02 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0097_addmodulecommand_selected_wf_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='lesson_stub',
            field=models.CharField(max_length=100, null=True, verbose_name='lesson_stub'),
        ),
    ]
