# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 22:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0098_workflow_lesson_stub'),
    ]

    operations = [
            migrations.RenameField('Workflow', 'lesson_stub', 'lesson_slug'),
    ]
