# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-12 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0099_workflow_lesson_stub_to_lesson_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='lesson_slug',
            field=models.CharField(max_length=100, null=True, verbose_name='lesson_slug'),
        ),
    ]
