# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-15 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0101_auto_20180607_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='module_library_collapsed',
        ),
    ]
