# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-18 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0103_auto_20180615_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='original_workflow_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='anonymous_owner_session_key',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='anonymous_owner_session_key'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='lesson_slug',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='lesson_slug'),
        ),
    ]
