# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-21 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0105_auto_20180619_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='wfmodule',
            name='has_unseen_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.RunSQL(['''
            UPDATE server_wfmodule
            SET has_unseen_notification = id IN (
                SELECT wf_module_id FROM server_notification
            )
        ''']),
        migrations.RemoveField(
            model_name='notification',
            name='wf_module',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
