# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0106_auto_20180621_2059'),
    ]

    operations = [
        migrations.RunSQL(['''
            UPDATE server_wfmodule
            SET has_unseen_notification = id IN (
                SELECT wf_module_id FROM server_notification
            )
        ''']),
    ]
