# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0107_auto_20180625_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wfmodule',
            name='has_unseen_notification',
            field=models.BooleanField(default=False, null=False),
        ),
        migrations.RemoveField(
            model_name='notification',
            name='wf_module',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
