# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-11 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    """
    Rewrite Python code to have a `def process(table):`.

    In the long run, we'll be able to download the Python-editor file to create
    a new Workbench module. Making the file more like a valid Python module is
    a first step.
    """

    dependencies = [
        ('server', '0108_auto_20180625_1946'),
    ]

    # Ooh my, ugly newlines:
    #
    # * sqlite3 has `CHAR(0x0a)` and no `'\n'`
    # * postgres has `CHR(0x0a)` or `'\n'`
    #
    # Because we support both, we can't use _any_ of those features. Instead,
    # we write actual newlines!
    operations = [
        migrations.RunSQL(["""
            UPDATE server_parameterval
            SET value = 'def process(table):
    ' || REPLACE(value, '
', '
    ')
            WHERE parameter_spec_id IN (
                SELECT id
                FROM server_parameterspec
                WHERE id_name = 'code'
                AND module_version_id IN (
                    SELECT id
                    FROM server_moduleversion
                    WHERE module_id IN (
                           SELECT id
                           FROM server_module
                           WHERE id_name = 'pythoncode'
                    )
                )
            )
        """])
    ]
