# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-16 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0109_auto_20180711_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='wfmodule',
            name='cached_render_result_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='wfmodule',
            name='cached_render_result_json',
            field=models.BinaryField(blank=True),
        ),
        migrations.AddField(
            model_name='wfmodule',
            name='cached_render_result_workflow_revision',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
