# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-17 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0111_wfmodule_cached_render_result_workflow_id'),
    ]

    operations = [
        migrations.RunSQL(["""
            DELETE FROM server_storedobject
            WHERE "type" = 'CACHED_TABLE'
        """])
        # We won't delete the files themselves in a migration. We'll do it
        # directly on the server: `rm *-cached.dat` or some-such.
    ]
