# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-17 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0112_auto_20180717_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storedobject',
            name='type',
        ),
    ]
