# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-13 22:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('server', '0113_remove_storedobject_type'),
    ]

    operations = [
        migrations.RenameField('WfModule', 'error_msg', 'fetch_error')
    ]
