# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0114_auto_20180813_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wfmodule',
            name='status',
        ),
        migrations.AddField(
            model_name='wfmodule',
            name='is_busy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='wfmodule',
            name='fetch_error',
            field=models.CharField(blank=True, max_length=200, verbose_name='fetch_error'),
        ),
    ]
