# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-15 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0115_auto_20180814_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameterspec',
            name='derived_data',
        ),
    ]
