# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-15 18:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0117_wfmodule_last_relevant_delta_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmodulecommand',
            name='dependent_wf_module_last_delta_ids',
            field=models.CharField(blank=True, max_length=99999, validators=[django.core.validators.int_list_validator]),
        ),
        migrations.AddField(
            model_name='changedataversioncommand',
            name='dependent_wf_module_last_delta_ids',
            field=models.CharField(blank=True, max_length=99999, validators=[django.core.validators.int_list_validator]),
        ),
        migrations.AddField(
            model_name='changeparametercommand',
            name='dependent_wf_module_last_delta_ids',
            field=models.CharField(blank=True, max_length=99999, validators=[django.core.validators.int_list_validator]),
        ),
        migrations.AddField(
            model_name='deletemodulecommand',
            name='dependent_wf_module_last_delta_ids',
            field=models.CharField(blank=True, max_length=99999, validators=[django.core.validators.int_list_validator]),
        ),
        migrations.AddField(
            model_name='reordermodulescommand',
            name='dependent_wf_module_last_delta_ids',
            field=models.CharField(blank=True, max_length=99999, validators=[django.core.validators.int_list_validator]),
        ),
    ]
