# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-15 19:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0118_auto_20180815_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wfmodule',
            old_name='cached_render_result_workflow_revision',
            new_name='cached_render_result_delta_id',
        ),
    ]
