# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-27 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0119_auto_20180815_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='has_zen_mode',
            field=models.BooleanField(default=False, verbose_name='has_zen_mode'),
        ),
    ]
