# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-05 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0121_workflow_in_all_users_workflow_lists'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='row_action_menu_entry_title',
            field=models.CharField(default='', max_length=200, verbose_name='row_action_menu_entry_title'),
        ),
    ]
