# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-13 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0122_module_row_action_menu_entry_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameterspec',
            old_name='def_menu_items',
            new_name='def_items',
        ),
        migrations.RenameField(
            model_name='parameterval',
            old_name='menu_items',
            new_name='items',
        ),
        migrations.AlterField(
            model_name='parameterspec',
            name='type',
            field=models.CharField(choices=[('statictext', 'Statictext'), ('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('button', 'Button'), ('checkbox', 'Checkbox'), ('menu', 'Menu'), ('column', 'Column'), ('multicolumn', 'Multiple columns'), ('radio', 'Radio'), ('secret', 'Secret'), ('custom', 'Custom')], default='string', max_length=16),
        ),
    ]
