# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-11 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0122_module_row_action_menu_entry_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='bucket',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='key',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
