# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-19 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0123_auto_20180911_1847'),
        ('server', '0123_auto_20180913_2011'),
    ]

    operations = [
    ]
