# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-20 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0124_merge_20180919_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wfmodule',
            name='fetch_error',
            field=models.CharField(blank=True, max_length=2000, verbose_name='fetch_error'),
        ),
    ]
