# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-20 20:38
from __future__ import unicode_literals

import os
import re
from django.conf import settings
from django.db import migrations, models
from server.minio import minio_client, UserFilesBucket


ext_re = re.compile('\.[0-9a-zA-Z]{1,4}\Z')


def move_uploadedfile_to_s3(uploadedfile):
    ext_match = ext_re.search(uploadedfile.name)

    if ext_match:
        ext = ext_match.group(0)  # '.csv', for instance
    else:
        ext = ''
    path = f'{settings.MEDIA_ROOT}/{uploadedfile.file}'

    uploadedfile.bucket = UserFilesBucket
    uploadedfile.key = f'{uploadedfile.uuid}{ext}'

    minio_client.fput_object(
        uploadedfile.bucket,
        uploadedfile.key,
        path,
        metadata={'Name': uploadedfile.name}
    )

    uploadedfile.save()

    os.unlink(path)


def move_uploadedfiles_to_s3(apps, schema_editor):
    UploadedFile = apps.get_model('server', 'UploadedFile')
    for uploadedfile in UploadedFile.objects.filter(file__isnull=False).all():
        move_uploadedfile_to_s3(uploadedfile)


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_squashed_0125_merge_20180919_1835'),
    ]

    operations = [
        migrations.RunPython(move_uploadedfiles_to_s3),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file',
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='bucket',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='uuid',
            field=models.CharField(max_length=255),
        ),
    ]
