# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-21 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0126_move_uploadedfile_to_s3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delta',
            name='command_description',
        ),
    ]
