# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-03 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0129_wfmodule_cached_render_result_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AclEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('can_edit', models.BooleanField(default=False)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='server.Workflow')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='aclentry',
            unique_together=set([('workflow', 'email')]),
        ),
    ]
