# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-16 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0132_initworkflowcommand'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='js_module',
            field=models.TextField(default='', verbose_name='js_module'),
        ),
    ]
