# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-16 21:06
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import server.models.commands


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0133_module_js_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeParametersCommand',
            fields=[
                ('delta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='server.Delta')),
                ('dependent_wf_module_last_delta_ids', models.CharField(blank=True, max_length=99999, validators=[django.core.validators.int_list_validator])),
                ('old_values', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='old_values')),
                ('new_values', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='new_values')),
                ('wf_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.WfModule')),
            ],
            options={
                'abstract': False,
            },
            bases=('server.delta', server.models.commands.util.ChangesWfModuleOutputs),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
