# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-13 16:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0134_changeparameterscommand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_workflows', to=settings.AUTH_USER_MODEL),
        ),
    ]
