# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-14 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0135_auto_20181113_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delta',
            name='next_delta',
        ),
        migrations.AlterField(
            model_name='delta',
            name='prev_delta',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='next_delta', to='server.Delta'),
        ),
    ]
