# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-14 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0136_auto_20181114_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addmodulecommand',
            name='applied',
        ),
        migrations.RemoveField(
            model_name='deletemodulecommand',
            name='applied',
        ),
    ]
