# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 16:11
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0138_auto_20181114_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmodulecommand',
            name='wf_module_delta_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=2), null=True, size=None),
        ),
        migrations.AddField(
            model_name='changedataversioncommand',
            name='wf_module_delta_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=2), null=True, size=None),
        ),
        migrations.AddField(
            model_name='changeparametercommand',
            name='wf_module_delta_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=2), null=True, size=None),
        ),
        migrations.AddField(
            model_name='changeparameterscommand',
            name='wf_module_delta_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=2), null=True, size=None),
        ),
        migrations.AddField(
            model_name='deletemodulecommand',
            name='wf_module_delta_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=2), null=True, size=None),
        ),
        migrations.AddField(
            model_name='reordermodulescommand',
            name='wf_module_delta_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=2), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='addmodulecommand',
            name='dependent_wf_module_last_delta_ids',
            field=models.CharField(blank=True, max_length=99999, null=True, validators=[django.core.validators.int_list_validator]),
        ),
        migrations.AlterField(
            model_name='changedataversioncommand',
            name='dependent_wf_module_last_delta_ids',
            field=models.CharField(blank=True, max_length=99999, null=True, validators=[django.core.validators.int_list_validator]),
        ),
        migrations.AlterField(
            model_name='changeparametercommand',
            name='dependent_wf_module_last_delta_ids',
            field=models.CharField(blank=True, max_length=99999, null=True, validators=[django.core.validators.int_list_validator]),
        ),
        migrations.AlterField(
            model_name='changeparameterscommand',
            name='dependent_wf_module_last_delta_ids',
            field=models.CharField(blank=True, max_length=99999, null=True, validators=[django.core.validators.int_list_validator]),
        ),
        migrations.AlterField(
            model_name='deletemodulecommand',
            name='dependent_wf_module_last_delta_ids',
            field=models.CharField(blank=True, max_length=99999, null=True, validators=[django.core.validators.int_list_validator]),
        ),
        migrations.AlterField(
            model_name='reordermodulescommand',
            name='dependent_wf_module_last_delta_ids',
            field=models.CharField(blank=True, max_length=99999, null=True, validators=[django.core.validators.int_list_validator]),
        ),
    ]
