# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-27 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0139_auto_20181123_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='wfmodule',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
