# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0139_auto_20181123_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmodulecommand',
            name='wf_module',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='server.WfModule'),
        ),
        migrations.AlterField(
            model_name='changedataversioncommand',
            name='wf_module',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='server.WfModule'),
        ),
        migrations.AlterField(
            model_name='changeparameterscommand',
            name='wf_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='server.WfModule'),
        ),
        migrations.AlterField(
            model_name='changewfmodulenotescommand',
            name='wf_module',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='server.WfModule'),
        ),
        migrations.AlterField(
            model_name='changewfmoduleupdatesettingscommand',
            name='wf_module',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='server.WfModule'),
        ),
        migrations.AlterField(
            model_name='deletemodulecommand',
            name='wf_module',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='server.WfModule'),
        ),
    ]
