# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-27 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0142_wfmodule_nix_cached_render_result_delta_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wfmodule',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wf_modules', to='server.Workflow'),
        ),
    ]
