# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0140_auto_20181128_1622'),
        ('server', '0143_auto_20181127_2202'),
    ]

    operations = [
    ]
