# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-29 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    """
    Clear undo history.

    Previous deltas had lots of problems:

    * If they had `wf_module` foreign keys and the WfModules were deleted
      (which was always an error), they'd set `wf_module=NULL` (which is
      unrecoverable).
    * If they had `dependent_wf_module_last_delta_ids` they'd depend on a
      pre-Tabs execution order.
    * There wasn't always an InitWorkflowCommand.
    * There was ChangeParameterCommand (which is too finicky to maintain).
    """

    dependencies = [
        ('server', '0144_merge_20181128_1900'),
    ]

    operations = [
        migrations.RunSQL([
            """
            DO $$
            BEGIN

            -- Delete all deltas
            DELETE FROM server_addmodulecommand;
            DELETE FROM server_changedataversioncommand;
            DELETE FROM server_changeparametercommand;
            DELETE FROM server_changeparameterscommand;
            DELETE FROM server_changewfmodulenotescommand;
            DELETE FROM server_changewfmoduleupdatesettingscommand;
            DELETE FROM server_changeworkflowtitlecommand;
            DELETE FROM server_deletemodulecommand;
            DELETE FROM server_reordermodulescommand;
            DELETE FROM server_initworkflowcommand;
            UPDATE server_workflow SET last_delta_id = NULL;
            DELETE FROM server_delta;

            -- Create new InitWorkflowCommands, one per workflow
            INSERT INTO server_delta
                (datetime, polymorphic_ctype_id, workflow_id)
            SELECT
                NOW(),
                (
                    SELECT id FROM django_content_type
                    WHERE app_label = 'server'
                    AND model = 'initworkflowcommand'
                ),
                id
            FROM server_workflow;

            INSERT INTO server_initworkflowcommand (delta_ptr_id)
            SELECT id FROM server_delta;

            -- Clean up deleted WfModules. This takes lots of DELETEs for
            -- dependent tables.
            DELETE FROM server_parameterval
            WHERE wf_module_id IN (
                SELECT id FROM server_wfmodule WHERE is_deleted
            );

            -- Leave written StoredObjects stranded. Not too nice.
            DELETE FROM server_storedobject
            WHERE wf_module_id IN (
                SELECT id FROM server_wfmodule WHERE is_deleted
            );

            -- Leave orphan UploadedFiles stranded. Also bad.
            DELETE FROM server_uploadedfile
            WHERE wf_module_id IN (
                SELECT id FROM server_wfmodule WHERE is_deleted
            );

            DELETE FROM server_wfmodule WHERE is_deleted;

            -- Invalidate all caches
            UPDATE server_workflow
            SET last_delta_id = (
                SELECT id FROM server_delta
                WHERE workflow_id = server_workflow.id
            );

            UPDATE server_wfmodule
            SET last_relevant_delta_id = (
                SELECT id FROM server_delta
                WHERE workflow_id = server_wfmodule.workflow_id
            );

            END$$;
            """
        ], reverse_sql=[])
    ]
