# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-05 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0149_nix_wf_module_workflow_id_20181130_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deletemodulecommand',
            name='selected_wf_module',
        ),
        migrations.AlterField(
            model_name='reordermodulescommand',
            name='tab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='server.Tab'),
        ),
        migrations.AlterField(
            model_name='wfmodule',
            name='tab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wf_modules', to='server.Tab'),
        ),
    ]
