kind: PersistentVolume
apiVersion: v1
metadata:
  name: all-nfs-data-pv
  namespace: staging
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    # Need absolute URL, not relative one: mount.nfs is run on the _node_,
    # not the pod, so the namespace ("production"/"staging") is not in the
    # DNS search domain. https://github.com/kubernetes/kubernetes/issues/44528
    server: nfs-server-service.staging.svc.cluster.local
    path: /
    readOnly: false
