apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  selector:
    matchLabels:
      app: backend-app
  strategy:
    type: Recreate
  replicas: 1
  revisionHistoryLimit: 20
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
        - name: backend
          image: "gcr.io/cj-workbench/backend:latest"
          resources:
            requests:
              cpu: 0.1
              memory: 256Mi
            limits:
              cpu: 0.75
              memory: 768Mi
          ports:
            - name: http
              containerPort: 8080
