# cloudsql docs say it should be a sidecar.
# But Kubernetes sidecars wreck pods' lifecycles.
# https://github.com/kubernetes/kubernetes/issues/25908#issuecomment-308569672
#
# As per https://github.com/kubernetes/enhancements/issues/753#issuecomment-713471597
# the issue won't be solved soon. So we'll wait. In the meantime, cloudsql-proxy will
# always connect using the cloudsql-proxy-sa account.
#
# TODO go with whatever future sidecar strategy Kubernetes uses, and delete the
# cloudsql-proxy-sa account.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudsql-proxy-deployment
spec:
  selector:
    matchLabels:
      app: cloudsql-proxy-app
  template:
    metadata:
      labels:
        app: cloudsql-proxy-app
    spec:
      serviceAccountName: cloudsql-proxy-sa
      containers:
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.18.0
          env:
            - name: PROJECT_NAME
              valueFrom:
                configMapKeyRef:
                  name: gcloud-config
                  key: PROJECT_NAME
          command:
            - "/cloud_sql_proxy"
            - "-ip_address_types=PRIVATE"
            - "-log_debug_stdout=true"
            - "-instances=$(PROJECT_NAME):us-central1:postgres=tcp:0.0.0.0:5432"
          securityContext:
            runAsNonRoot: true
---
kind: Service
apiVersion: v1
metadata:
  name: cloudsql-proxy
spec:
  selector:
    app: cloudsql-proxy-app
  ports:
    - protocol: TCP
      port: 5432
