apiVersion: apps/v1
kind: Deployment
metadata:
  name: cron-lesson-autoupdate-disabler-deployment
spec:
  selector:
    matchLabels:
      app: cron-lesson-autoupdate-disabler-app
  strategy:
    type: Recreate
  replicas: 1
  revisionHistoryLimit: 20
  template:
    metadata:
      labels:
        app: cron-lesson-autoupdate-disabler-app
    spec:
      serviceAccountName: cron-sa
      containers:
        - name: cron
          image: "gcr.io/workbenchdata-ci/cron:latest"
          command: [ "bin/cron-lesson-autoupdate-disabler" ]
          resources:
            requests:
              cpu: 0.1
              memory: 200Mi
            limits:
              cpu: 0.1
              memory: 200Mi
          env:
            - name: CJW_PRODUCTION
              value: 'True'
            - name: PYTHONUNBUFFERED
              value: '1'
            - name: CJW_DB_HOST
              value: localhost  # cloud-sql-proxy
            - name: CJW_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-cjworkbench-credentials
                  key: password
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.18.0
          env:
            - name: PROJECT_NAME
              valueFrom:
                configMapKeyRef:
                  name: gcloud-config
                  key: PROJECT_NAME
          command:
            - "/cloud_sql_proxy"
            - "-ip_address_types=PRIVATE"
            - "-log_debug_stdout=true"
            - "-instances=$(PROJECT_NAME):us-central1:postgres=tcp:5432"
            - "-term_timeout=10s"
          securityContext:
            runAsNonRoot: true
