apiVersion: apps/v1
kind: Deployment
metadata:
  name: cron-deployment
spec:
  selector:
    matchLabels:
      app: cron-app
  strategy:
    type: Recreate
  replicas: 1
  revisionHistoryLimit: 20
  template:
    metadata:
      labels:
        app: cron-app
    spec:
      containers:
        - name: cron
          image: "gcr.io/workbenchdata-ci/cron:latest"
          resources:
            requests:
              cpu: 0.1
              memory: 200Mi
            limits:
              cpu: 0.1
              memory: 200Mi
          env:
            - name: CJW_PRODUCTION
              value: 'True'
            - name: PYTHONUNBUFFERED
              value: '1'
            - name: ASGI_THREADS
              value: '2'
            - name: CJW_DB_HOST
              value: database-service
            - name: CJW_DB_PASSWORD
              value: cjworkbench
            - name: CJW_SECRET_KEY
              value: cron-needs-no-secret-key
            - name: CJW_SENDGRID_API_KEY
              value: cron-needs-no-sendgrid-config
            - name: CJW_SENDGRID_CONFIRMATION_ID
              value: cron-needs-no-sendgrid-config
            - name: CJW_SENDGRID_PASSWORD_RESET_ID
              value: cron-needs-no-sendgrid-config
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-access-key
                  key: access_key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-access-key
                  key: secret_key
            - name: MINIO_BUCKET_PREFIX
              value: ""
            - name: MINIO_URL
              value: http://minio-service
            - name: MINIO_BUCKET_SUFFIX
              valueFrom:
                configMapKeyRef:
                  name: workbench-config
                  key: domainNameWithLeadingDot
            - name: MINIO_EXTERNAL_URL
              value: "https://user-files$(MINIO_BUCKET_SUFFIX)"
            - name: _RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-1-rabbitmq-secret
                  key: rabbitmq-pass
            - name: CJW_RABBITMQ_HOST
              value: "amqp://rabbit:$(_RABBITMQ_PASSWORD)@rabbitmq-1-rabbitmq-svc/"
