kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dbdata-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard
