apiVersion: apps/v1
kind: Deployment
metadata:
  name: fetcher-deployment
spec:
  selector:
    matchLabels:
      app: fetcher-app
  replicas: 2
  revisionHistoryLimit: 20
  template:
    metadata:
      labels:
        app: fetcher-app
    spec:
      containers:
        - name: fetcher
          image: "gcr.io/cj-workbench/fetcher:latest"
          resources:
            # fetch() functions are usually network-constrained: CPU and RAM
            # usage are low.
            #
            # [2019-10-31, adamhooper] before today, loadurl could consume lots
            # of RAM but usually it didn't; so we ran multiple fetches at the
            # same time on the same machine to make use of all the RAM we were
            # declaring. We used to run 3 fetchers on a container with 1 CPU
            # and 5.2Gi RAM. Now RAM usage has dropped, so I'm lowering CPU
            # usage to get us roughly the same amount of resources.
            requests:
              cpu: 0.3
              memory: 1.2Gi
            limits:
              cpu: 0.3
              memory: 1.2Gi
          env:
            - name: CJW_PRODUCTION
              value: 'True'
            - name: PYTHONUNBUFFERED
              value: '1'
            - name: ASGI_THREADS
              value: '4'
            - name: CJW_N_FETCHERS
              value: '4'
            - name: CJW_DB_HOST
              value: database-service
            - name: CJW_DB_PASSWORD
              value: cjworkbench
            - name: CJW_SECRET_KEY
              value: fetcher-needs-no-secret-key
            - name: CJW_SENDGRID_API_KEY
              value: fetcher-needs-no-sendgrid-config
            - name: CJW_SENDGRID_CONFIRMATION_ID
              value: fetcher-needs-no-sendgrid-config
            - name: CJW_SENDGRID_PASSWORD_RESET_ID
              value: fetcher-needs-no-sendgrid-config
            - name: CJW_GOOGLE_CLIENT_SECRETS
              value: secrets/google-oauth-secret/google-oauth-secret.json
            - name: CJW_INTERCOM_CLIENT_SECRETS
              value: secrets/intercom-oauth-secret/intercom-oauth-secret.json
            - name: CJW_SOCIALACCOUNT_SECRETS
              value: secrets/socialaccount-secrets/socialaccount-secrets.json
            - name: CJW_TWITTER_CLIENT_SECRETS
              value: secrets/twitter-oauth-secret/twitter-oauth-secret.json
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-access-key
                  key: access_key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-access-key
                  key: secret_key
            - name: MINIO_BUCKET_PREFIX
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MINIO_EXTERNAL_URL
              valueFrom:
                secretKeyRef:
                  name: minio-access-key
                  key: external_url
            - name: MINIO_URL
              value: http://minio-service
            - name: MINIO_BUCKET_SUFFIX
              value: '.workbenchdata.com'
            - name: _RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-1-rabbitmq-secret
                  key: rabbitmq-pass
            - name: CJW_RABBITMQ_HOST
              value: "amqp://rabbit:$(_RABBITMQ_PASSWORD)@rabbitmq-1-rabbitmq-svc/"
          volumeMounts:
            - mountPath: /app/secrets/google-oauth-secret
              name: google-oauth-secret
              readOnly: true
            - mountPath: /app/secrets/intercom-oauth-secret
              name: intercom-oauth-secret
              readOnly: true
            - mountPath: /app/secrets/socialaccount-secrets
              name: socialaccount-secrets
              readOnly: true
            - mountPath: /app/secrets/twitter-oauth-secret
              name: twitter-oauth-secret
              readOnly: true
      volumes:
        - name: google-oauth-secret
          secret:
            secretName: google-oauth-secret
            items:
              - key: json
                path: google-oauth-secret.json
        - name: intercom-oauth-secret
          secret:
            secretName: intercom-oauth-secret
            items:
              - key: json
                path: intercom-oauth-secret.json
        - name: socialaccount-secrets
          secret:
            secretName: socialaccount-secrets
            items:
              - key: json
                path: socialaccount-secrets.json
        - name: twitter-oauth-secret
          secret:
            secretName: twitter-oauth-secret
            items:
              - key: json
                path: twitter-oauth-secret.json
