apiVersion: apps/v1
kind: Deployment
metadata:
  name: fetcher-deployment
spec:
  selector:
    matchLabels:
      app: fetcher-app
  replicas: 2
  revisionHistoryLimit: 20
  template:
    metadata:
      labels:
        app: fetcher-app
    spec:
      initContainers:
        # setup-sandboxes.sh needs special privileges; run it in an init container.
        #
        # We run this command separately because it runs with privileged: true.
        # (pyspawner shouldn't have permission to fiddle with the mount
        # namespace, lest malicious code use that permission to somehow escape
        # its sandbox.)
        #
        # See https://itnext.io/using-overlay-mounts-with-kubernetes-960375c05959
        - name: setup-sandboxes
          image: "gcr.io/cj-workbench/migrate:latest"
          securityContext:
            privileged: true  # so it can run mount and iptables
          command: [ "bash", "-x", "/app/cjwkernel/setup-sandboxes.sh", "all" ]
          volumeMounts:
            - mountPath: /var/lib/cjwkernel/chroot
              name: chroot
              mountPropagation: Bidirectional  # expose mounts to main app
      containers:
        - name: fetcher
          image: "gcr.io/cj-workbench/fetcher:latest"
          resources:
            # fetch() functions are usually network-constrained: CPU and RAM
            # usage are low.
            #
            # [2019-10-31, adamhooper] before today, loadurl could consume lots
            # of RAM but usually it didn't; so we ran multiple fetches at the
            # same time on the same machine to make use of all the RAM we were
            # declaring. We used to run 3 fetchers on a container with 1 CPU
            # and 5.2Gi RAM. Now RAM usage has dropped, so I'm lowering CPU
            # usage to get us roughly the same amount of resources.
            requests:
              cpu: 0.3
              memory: 1.2Gi
            limits:
              cpu: 0.3
              memory: 1.2Gi
          env:
            - name: CJW_PRODUCTION
              value: 'True'
            - name: PYTHONUNBUFFERED
              value: '1'
            - name: ASGI_THREADS
              value: '2'
            - name: CJW_DB_HOST
              value: database-service
            - name: CJW_DB_PASSWORD
              value: cjworkbench
            - name: CJW_SECRET_KEY
              value: fetcher-needs-no-secret-key
            - name: CJW_SENDGRID_API_KEY
              value: fetcher-needs-no-sendgrid-config
            - name: CJW_SENDGRID_CONFIRMATION_ID
              value: fetcher-needs-no-sendgrid-config
            - name: CJW_SENDGRID_PASSWORD_RESET_ID
              value: fetcher-needs-no-sendgrid-config
            - name: CJW_GOOGLE_CLIENT_SECRETS
              value: secrets/google-oauth-secret/google-oauth-secret.json
            - name: CJW_INTERCOM_CLIENT_SECRETS
              value: secrets/intercom-oauth-secret/intercom-oauth-secret.json
            - name: CJW_TWITTER_CLIENT_SECRETS
              value: secrets/twitter-oauth-secret/twitter-oauth-secret.json
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-access-key
                  key: access_key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-access-key
                  key: secret_key
            - name: MINIO_BUCKET_PREFIX
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MINIO_EXTERNAL_URL
              valueFrom:
                secretKeyRef:
                  name: minio-access-key
                  key: external_url
            - name: MINIO_URL
              value: http://minio-service
            - name: MINIO_BUCKET_SUFFIX
              value: '.workbenchdata.com'
            - name: _RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-1-rabbitmq-secret
                  key: rabbitmq-pass
            - name: CJW_RABBITMQ_HOST
              value: "amqp://rabbit:$(_RABBITMQ_PASSWORD)@rabbitmq-1-rabbitmq-svc/"
          volumeMounts:
            - mountPath: /app/secrets/google-oauth-secret
              name: google-oauth-secret
              readOnly: true
            - mountPath: /app/secrets/intercom-oauth-secret
              name: intercom-oauth-secret
              readOnly: true
            - mountPath: /app/secrets/twitter-oauth-secret
              name: twitter-oauth-secret
              readOnly: true
            - mountPath: /var/lib/cjwkernel/chroot
              name: chroot
          securityContext:
            capabilities:
              add:
                - NET_ADMIN # To create network interface for sandbox in cjwkernel
        - name: teardown-sandboxes
          # "any volume mounts created by Containers in Pods must be destroyed
          # (unmounted) by the Containers on termination"
          # -- https://kubernetes.io/docs/concepts/storage/volumes/#mount-propagation
          image: "gcr.io/cj-workbench/migrate:latest"
          command: ["sh", "-c", "sleep infinity"]  # do nothing, until exit. (sh responds to INT signal)
          securityContext:
            privileged: true  # so it can unmount
          lifecycle:
            preStop:
              exec:
                command: ["bash", "-x", "/app/cjwkernel/teardown-sandboxes.sh"]
          volumeMounts:
            - mountPath: /var/lib/cjwkernel/chroot
              name: chroot
              mountPropagation: Bidirectional  # expose mounts to main app
      volumes:
        - name: google-oauth-secret
          secret:
            secretName: google-oauth-secret
            defaultMode: 0400
            items:
              - key: json
                path: google-oauth-secret.json
        - name: intercom-oauth-secret
          secret:
            secretName: intercom-oauth-secret
            defaultMode: 0400
            items:
              - key: json
                path: intercom-oauth-secret.json
        - name: twitter-oauth-secret
          secret:
            secretName: twitter-oauth-secret
            defaultMode: 0400
            items:
              - key: json
                path: twitter-oauth-secret.json
        - name: chroot
          emptyDir: {}
