kind: Service
apiVersion: v1
metadata:
  name: frontend-service
  annotations:
    cloud.google.com/neg: '{"ingress": true}'  # https://cloud.google.com/kubernetes-engine/docs/how-to/container-native-load-balancing
    beta.cloud.google.com/backend-config: '{"ports": {"80": "websockets-backend-config"}}'
spec:
  selector:
    app: frontend-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
