---
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: app-cert
spec:
  domains:
    - app.workbenchdata-staging.com
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: minio-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: app-ip
    networking.gke.io/managed-certificates: app-cert
spec:
  backend:
    serviceName: minio-service
    servicePort: 80
