---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: frontend-frontend-config
spec:
  redirectToHttps:
    enabled: true
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: websockets-backend-config
spec:
  timeoutSec: 3600
  connectionDraining:
    drainingTimeoutSec: 30
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: app-ip
    networking.gke.io/managed-certificates: app-cert
    networking.gke.io/v1beta1.FrontendConfig: frontend-frontend-config
spec:
  backend:
    serviceName: frontend-service
    servicePort: 80
  rules:
  - http:
      # Deny access to /tusd-hooks
      # See server/urls.py: tusd sends requests here, and frontend trusts
      # that requests to /tusd-hooks are from the internal tusd service.
      # TODO make tusd-hooks a different service
      paths:
      - path: /tusd-hooks
        pathType: Prefix  # Don't trust Django: it might serve "/tusd-hooks/" if we didn't use Prefix
        backend:
          serviceName: http-404-service
          servicePort: 80
