apiVersion: v1
kind: ConfigMap
metadata:
  name: http-404-config
data:
  404.http: |
    HTTP/1.1 404 Not Found
    Cache-Control: no-cache
    Connection: close
    Content-Type: text/plain; charset=ascii

    You requested a page that does not exist.
  haproxy.cfg: |
    # We use haproxy to redirect HTTP to HTTPS. (Django is inefficient at this.)
    global
        nbproc 1
        nbthread 1
        log stdout format raw local0 info

    defaults
        log global
        timeout connect 10s
        timeout client 60s
        timeout server 10s
        timeout tunnel 10s
        timeout client-fin 10s
        mode http
        option httplog

    frontend httporhttps
        bind *:8080
        http-request deny deny_status 200 if { path /healthz }
        default_backend always404

    backend always404
        errorfile 503 /usr/local/etc/haproxy/404.http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-404-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: http-404-app
  template:
    metadata:
      labels:
        app: http-404-app
    spec:
      containers:
      - name: http-404
        image: "haproxy:2.1.2"
        command: [ "haproxy", "-f", "/usr/local/etc/haproxy/haproxy.cfg", "-m", "90", "-db" ]
        resources:
          requests:
            cpu: 0.1
            memory: 100Mi
          limits:
            memory: 100Mi
        ports:
          - name: http
            containerPort: 8080
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
        volumeMounts:
        - mountPath: /usr/local/etc/haproxy/haproxy.cfg
          name: http-404-config
          subPath: haproxy.cfg
        - mountPath: /usr/local/etc/haproxy/404.http
          name: http-404-config
          subPath: 404.http
      volumes:
      - name: http-404-config
        configMap:
          name: http-404-config
