apiVersion: batch/v1
kind: Job
metadata:
  name: init-nfs-data-job
spec:
  template:
    metadata:
      labels:
        app: init-nfs-data-app
    spec:
      restartPolicy: Never
      containers:
        - name: init-nfs-data
          image: debian
          command: [ 'mkdir', '-p', '/mnt/saveddata', '/mnt/importedmodules' ]
          volumeMounts:
            - mountPath: /mnt
              name: all-nfs-data-pv
      volumes:
        - name: all-nfs-data-pv
          persistentVolumeClaim:
            claimName: all-nfs-data-pvc
