apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-job
spec:
  template:
    metadata:
      labels:
        app: migrate-app
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: "gcr.io/cj-workbench/migrate:latest"
          env:
            - name: CJW_PRODUCTION
              value: 'True'
            - name: PYTHONUNBUFFERED
              value: '1'
            - name: ASGI_THREADS
              value: '5'
            - name: CJW_DB_HOST
              value: database-service
            - name: CJW_RABBITMQ_HOST
              value: amqp://guest:guest@rabbitmq-service/
            - name: CJW_DB_PASSWORD
              value: cjworkbench
            - name: CJW_SECRET_KEY
              value: migrate-needs-no-secret-key
            - name: CJW_MOCK_EMAIL
              value: 'True'
            - name: CJW_SOCIALACCOUNT_SECRETS
              value: secrets/socialaccount-secrets/socialaccount-secrets.json
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-access-key
                  key: access_key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-access-key
                  key: secret_key
            - name: MINIO_BUCKET_PREFIX
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MINIO_EXTERNAL_URL
              valueFrom:
                secretKeyRef:
                  name: minio-access-key
                  key: external_url
            - name: MINIO_URL
              value: 'http://minio-service'
            - name: MINIO_BUCKET_SUFFIX
              value: '.workbenchdata.com'
          volumeMounts:
            # TODO Find a way to load_socialaccounts? Depending on a secret takes a lot of config
            - mountPath: /app/secrets/socialaccount-secrets
              name: socialaccount-secrets
              readOnly: true
      volumes:
        - name: socialaccount-secrets
          secret:
            secretName: socialaccount-secrets
            items:
              - key: json
                path: socialaccount-secrets.json
