apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-job
spec:
  template:
    metadata:
      labels:
        app: migrate-app
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: "gcr.io/cj-workbench/migrate:latest"
          env:
            - name: CJW_PRODUCTION
              value: 'True'
            - name: CJW_DB_HOST
              value: database-service
            - name: CJW_REDIS_HOST
              value: redis-service
            - name: CJW_DB_PASSWORD
              value: cjworkbench
            - name: CJW_SECRET_KEY
              value: migrate-needs-no-secret-key
            - name: CJW_MOCK_EMAIL
              value: 'True'
            - name: CJW_SOCIALACCOUNT_SECRETS
              value: secrets/socialaccount-secrets/socialaccount-secrets.json
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-access-key
                  key: access_key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-access-key
                  key: secret_key
            - name: MINIO_BUCKET_PREFIX
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MINIO_EXTERNAL_URL
              valueFrom:
                secretKeyRef:
                  name: minio-access-key
                  key: external_url
            - name: MINIO_BUCKET_SUFFIX
              value: '.workbenchdata.com'
          volumeMounts:
            # TODO make sure no migrations depend on mounted volumes, then nix mounts
            - mountPath: /app/importedmodules
              name: importedmodules-pv
            - mountPath: /app/media
              name: saveddata-pv
            # TODO Find a way to load_socialaccounts? Depending on a secret takes a lot of config
            - mountPath: /app/secrets/socialaccount-secrets
              name: socialaccount-secrets
              readOnly: true
      volumes:
        - name: importedmodules-pv
          persistentVolumeClaim:
            claimName: importedmodules-pvc
        - name: saveddata-pv
          persistentVolumeClaim:
            claimName: saveddata-pvc
        - name: socialaccount-secrets
          secret:
            secretName: socialaccount-secrets
            items:
              - key: json
                path: socialaccount-secrets.json
