apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server-deployment
spec:
  selector:
    matchLabels:
      app: nfs-server-app
  template:
    metadata:
      labels:
        app: nfs-server-app
    spec:
      containers:
        - name: nfs-server
          image: "k8s.gcr.io/volume-nfs:0.8"
          resources:
            limits:
              cpu: 0.1
              memory: 256Mi
          ports:
            - name: nfs
              containerPort: 2049
            - name: mountd
              containerPort: 20048
            - name: rpcbind
              containerPort: 111
          securityContext:
            # https://github.com/kubernetes/examples/blob/master/staging/volumes/nfs/nfs-server-rc.yaml
            privileged: true
          volumeMounts:
            - mountPath: /exports
              name: exports-volume
      volumes:
        - name: exports-volume
          persistentVolumeClaim:
            claimName: nfs-server-pvc
