apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: public-ingress
  namespace: production
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
      - app2.workbenchdata.com
      secretName: app2.workbenchdata.com-secret
  rules:
    - host: app2.workbenchdata.com
      http:
        paths:
          - path: /
            backend:
              serviceName: frontend-service
              servicePort: 80
