apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  selector:
    matchLabels:
      app: redis-app
  strategy:
    type: Recreate
  replicas: 1
  revisionHistoryLimit: 20
  template:
    metadata:
      labels:
        app: redis-app
    spec:
      containers:
        - name: redis
          image: "redis:4.0.10"
          resources:
            requests:
              cpu: 0.1
              memory: 256Mi
            limits:
              cpu: 0.1
              memory: 768Mi
