apiVersion: apps/v1
kind: Deployment
metadata:
  name: renderer-deployment
spec:
  selector:
    matchLabels:
      app: renderer-app
  replicas: 2
  revisionHistoryLimit: 20
  template:
    metadata:
      labels:
        app: renderer-app
    spec:
      serviceAccountName: renderer-sa
      nodeSelector: # Only schedule on nodes that disallow SMT. (Pod runs untrusted user code.)
        cloud.google.com/gke-smt-disabled: "true"
      tolerations: # Allow scheduling on preemptible nodes. (Work is expensive to run, cheap to retry.)
      - key: preemptible
        operator: Equal
        value: "true"
        effect: NoSchedule
      affinity: # Move to preemptible nodes whenever one is available
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: cloud.google.com/gke-preemptible
                operator: In
                values: [ "true" ]
      initContainers:
        # setup-sandboxes.sh needs special privileges; run it in an init container.
        #
        # We run this command separately because it runs with privileged: true.
        # (pyspawner shouldn't have permission to fiddle with the mount
        # namespace, lest malicious code use that permission to somehow escape
        # its sandbox.)
        #
        # See https://itnext.io/using-overlay-mounts-with-kubernetes-960375c05959
        - name: setup-sandboxes
          image: "gcr.io/workbenchdata-ci/migrate:latest"
          securityContext:
            privileged: true  # so it can run mount and iptables
          command: [ "bash", "-x", "/app/cjwkernel/setup-sandboxes.sh", "all" ]
          volumeMounts:
            - mountPath: /var/lib/cjwkernel/chroot
              name: chroot
              mountPropagation: Bidirectional  # expose mounts to main app
      containers:
        - name: renderer
          image: "gcr.io/workbenchdata-ci/renderer:latest"
          resources:
            # Request exactly 1 CPU and tons of RAM. render() functions are
            # synchronous.
            requests:
              cpu: 1
              memory: 5.5Gi
            limits:
              cpu: 1
              memory: 5.5Gi
          env:
            - name: CJW_PRODUCTION
              value: 'True'
            - name: PYTHONUNBUFFERED
              value: '1'
            - name: ASGI_THREADS
              value: '2'
            - name: CJW_DB_HOST
              value: localhost  # cloud-sql-proxy
            - name: CJW_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-cjworkbench-credentials
                  key: password
            - name: CJW_SECRET_KEY
              value: renderer-needs-no-secret-key
            - name: CJW_SENDGRID_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cjw-sendgrid-api-key
                  key: value
            - name: CJW_SENDGRID_CONFIRMATION_ID
              value: d-cf03717d432e46d38e0b6b5b19f80b57
            - name: CJW_SENDGRID_PASSWORD_RESET_ID
              value: d-7cc8e91286bb4c87a9484f331407568a
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-access-key
                  key: access_key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-access-key
                  key: secret_key
            - name: MINIO_BUCKET_PREFIX
              value: ""
            - name: MINIO_URL
              value: http://minio-service
            - name: MINIO_BUCKET_SUFFIX
              valueFrom:
                configMapKeyRef:
                  name: workbench-config
                  key: domainNameWithLeadingDot
            - name: MINIO_EXTERNAL_URL
              value: "https://user-files$(MINIO_BUCKET_SUFFIX)"
            - name: _RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-1-rabbitmq-secret
                  key: rabbitmq-pass
            - name: CJW_RABBITMQ_HOST
              value: "amqp://rabbit:$(_RABBITMQ_PASSWORD)@rabbitmq-1-rabbitmq-svc/"
          volumeMounts:
            - mountPath: /var/lib/cjwkernel/chroot
              name: chroot
          securityContext:
            capabilities:
              add:
                # TODO ban render() from networking. Period. Then nix NET_ADMIN priv.
                - NET_ADMIN # To create network interface for sandbox in cjwkernel
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.18.0
          env:
            - name: PROJECT_NAME
              valueFrom:
                configMapKeyRef:
                  name: gcloud-config
                  key: PROJECT_NAME
          command:
            - "/cloud_sql_proxy"
            - "-ip_address_types=PRIVATE"
            - "-log_debug_stdout=true"
            - "-instances=$(PROJECT_NAME):us-central1:postgres=tcp:5432"
          securityContext:
            runAsNonRoot: true
        - name: teardown-sandboxes
          # "any volume mounts created by Containers in Pods must be destroyed
          # (unmounted) by the Containers on termination"
          # -- https://kubernetes.io/docs/concepts/storage/volumes/#mount-propagation
          image: "gcr.io/workbenchdata-ci/migrate:latest"
          command: ["sh", "-c", "sleep infinity"]  # do nothing, until exit. (sh responds to INT signal)
          securityContext:
            privileged: true  # so it can unmount
          lifecycle:
            preStop:
              exec:
                command: ["bash", "-x", "/app/cjwkernel/teardown-sandboxes.sh"]
          volumeMounts:
            - mountPath: /var/lib/cjwkernel/chroot
              name: chroot
              mountPropagation: Bidirectional  # expose mounts to main app
      volumes:
        - name: chroot
          emptyDir: {}
