apiVersion: apps/v1
kind: Deployment
metadata:
  name: renderer-deployment
spec:
  selector:
    matchLabels:
      app: renderer-app
  replicas: 2
  revisionHistoryLimit: 20
  template:
    metadata:
      labels:
        app: renderer-app
    spec:
      containers:
        - name: renderer
          image: "gcr.io/cj-workbench/renderer:latest"
          resources:
            # Request exactly 1 CPU and tons of RAM. render() functions are
            # synchronous.
            requests:
              cpu: 1
              memory: 5250Mi # basically the max on an n1-standard-2 running fluentd
            limits:
              cpu: 1
              memory: 5250Mi
          env:
            - name: CJW_PRODUCTION
              value: 'True'
            - name: PYTHONUNBUFFERED
              value: '1'
            - name: ASGI_THREADS
              value: '2'
            - name: CJW_N_RENDERERS
              value: '1'
            - name: CJW_DB_HOST
              value: database-service
            - name: CJW_DB_PASSWORD
              value: cjworkbench
            - name: CJW_SECRET_KEY
              value: renderer-needs-no-secret-key
            - name: CJW_SENDGRID_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cjw-sendgrid-api-key
                  key: value
            - name: CJW_SENDGRID_CONFIRMATION_ID
              value: d-cf03717d432e46d38e0b6b5b19f80b57
            - name: CJW_SENDGRID_PASSWORD_RESET_ID
              value: d-7cc8e91286bb4c87a9484f331407568a
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-access-key
                  key: access_key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-access-key
                  key: secret_key
            - name: MINIO_BUCKET_PREFIX
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MINIO_EXTERNAL_URL
              valueFrom:
                secretKeyRef:
                  name: minio-access-key
                  key: external_url
            - name: MINIO_URL
              value: http://minio-service
            - name: MINIO_BUCKET_SUFFIX
              value: '.workbenchdata.com'
            - name: _RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-1-rabbitmq-secret
                  key: rabbitmq-pass
            - name: CJW_RABBITMQ_HOST
              value: "amqp://rabbit:$(_RABBITMQ_PASSWORD)@rabbitmq-1-rabbitmq-svc/"
