kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: saveddata-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ''
  resources:
    requests:
      storage: 97Gi
  selector:
    matchLabels:
      implementation: nfs-server
