kind: PersistentVolume
apiVersion: v1
metadata:
  name: saveddata-pv
spec:
  capacity:
    storage: 18Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /app/media
    server: nfs
    readOnly: false
