name: Deploy staging on master checks pass

on:
  check_suite:
    branches: [master]
    types: [completed]

jobs:
  kubectl-deploy:
    name: Deploy to staging Kubernetes cluster
    runs-on: ubuntu-latest
    if: github.event.check_suite.conclusion == 'success'
    steps:
      - name: Notify Slack we are about to start
        uses: CJWorkbench/slack-postmessage@9a028913e74e93a19032da68a9b4def4106a46e3
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        with:
          message: '{"channel": "#staging-status", "text": "Deploying `${{ github.sha }}` to staging…"}'

      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: CJWorkbench/cjworkbench-deploy@main

      - name: Install GCloud API
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          version: '347.0.0'
          service_account_email: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Set up Kustomize
        run: |-
          curl -sfLo /usr/local/bin/kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v4.0.6/kustomize_4.0.6_linux_amd64
          chmod +x /usr/local/bin/kustomize

      - name: Run kubectl
        env:
          GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
          GCP_REGION: ${{ secrets.GCP_REGION }}
          GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          gcloud container clusters get-credentials "$GKE_CLUSTER" \
            --region "$GCP_REGION" \
            --project "$GCP_PROJECT"
          gcloud --quiet components install kubectl
          deploy/advanced-deploy staging "$GITHUB_SHA"

      - name: Notify Slack we did it
        uses: CJWorkbench/slack-postmessage@9a028913e74e93a19032da68a9b4def4106a46e3
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        with:
          message: '{"channel": "#staging-status", "text": "Deployed `${{ github.sha }}` to https://app.workbenchdata-staging.com"}'
